### ISSUE TITLE
Cannot assing multiple keys combinations

### ISSUE THREAD

**Issue by MR-Diamond** [bk138/gromit-mpx#107]
Hi, I read the manual, but I cannot figure out if is possible.

I edited `~/.config/gromit-mpx.cfg`

and added `HOTKEY = "Control_L+1";` to use left Control key in combination with 1 key on the keyboard, but when I launch gromit in a  terminal window I get `cannot find the key "Control_L+1"`
I also tried `Control_L, 1` `Control_L-1` and `Control_L 1` but is still not accepted.

All is fine if I left only `Control_L` 

Apart of this, Gormit complains about the fact that F9 and F8 are not usable:
![Screenshot_2020-11-18_20-37-17](https://user-images.githubusercontent.com/32249442/99579553-9d17e700-29de-11eb-8a2d-032efc40b5dc.png)
![Screenshot_2020-11-18_20-37-31](https://user-images.githubusercontent.com/32249442/99579559-9ee1aa80-29de-11eb-8cd2-cdffe56638bc.png)

So, at least, I would cheange hotkeys to get rid of these warnings every time that I launch Gromit...

**Comment by MR-Diamond** [comment]
Thank you: at least, by looking the pointed commit, I have been able to get rid of warning messages by using:

```
HOTKEY = "";
UNDOKEY = "";
```

There are plans to implement the ability of using key combos?

**Comment by bk138** [comment]
> There are plans to implement the ability of using key combos?

No, as Gromit-MPX already uses combos for the single hot keys by adding Shift, Ctrl, etc, please see https://github.com/bk138/gromit-mpx#how-to-use-it

**Comment by bk138** [comment]
> Thank you: at least, by looking the pointed commit, I have been able to get rid of warning messages by using:
> 
> ```
> HOTKEY = "";
> UNDOKEY = "";
> ```

This way, you won't be able to leave annotation mode, so I suggest you define some hotkey that's not a function key.

**Comment by MR-Diamond** [comment]
I solved by using `xbindkeys` :

```
# Gromit: toggle
"gromit-mpx --toggle"
control + 1

# Gromit: clear
"gromit-mpx --clear"
control + 2

# Gromit: undo
"gromit-mpx --undo"
control + 3

# Gromit: quit
#gromit-mpx --quit
control + 4
```
