### ISSUE TITLE
libappindicator3 deprecated, need to switch to libayatana-appindicator3

### ISSUE THREAD

**Issue by barak** [bk138/gromit-mpx#111]
This is a bug reported against the Debian package, see https://bugs.debian.org/956769

> ... libappindicator3-dev is is deprecated and unmaintained. The supported replacement appears to be
libayatana-appindicator3-dev.

**Comment by bk138** [comment]
Hi @barak yeah I saw that. I assume libayatana-appindicator3-dev to be a drop-in replacement providing the same API, so that is something related to the Debian packaging only? If not, what can I do?

**Comment by barak** [comment]
I think this is an upstream change, not Debian-specific.

Just tried switching, seems to work. Give it a shot? bc8860e

**Comment by bk138** [comment]
I tried with a similar approach, but this broke the current [Flatpak packaging](https://github.com/bk138/gromit-mpx/blob/master/flatpak/net.christianbeier.Gromit-MPX.yml). I probably have to build the ayatana appindicator there in the build process.

**Comment by bk138** [comment]
I see there is https://sources.debian.org/patches/gromit-mpx/1.4-2/0001-switch-from-deprecated-appindicator3-to-ayatana-appi.patch/ for the time being, will tackle this for 1.5.

**Comment by barak** [comment]
Yeah, it was a release-critical issue for Debian and the patch was trivial.

Took a quick look at flatpak, I think they do not yet support this change, although adding support for it appears very straightforward. I suppose gromit-mpx could have a configuration option with `#ifdef`s, etc, to maintain legacy support for the old library for things like flatpak.
