### ISSUE TITLE
Cannot set HOTKEY or UNDOKEY in .cfg file on XFCE

### ISSUE THREAD

**Issue by cshelton** [bk138/gromit-mpx#113]
A line like
`HOTKEY = "Super_L";`
in the .cfg file has no effect under XFCE.

To reproduce:
Edit .cfg file in ~/config/gromit-mpx.cfg to add above line.  Run program under XFCE.

Culprit seems to be the condition `g_strcmp0(data->hot_keyval, DEFAULT_HOTKEY) == 0` on line 395 (and the similar condition on line 399 for UNDOKEY).  

My solution is to remove these conditions.  However, if it is intended that only the first edit of the HOTKEY take precedent, then something more involved must be implemented.  At this point in the code, data->hot_keyval has been changed (because XFCE) but the #define string DEFAULT_HOTKEY has not.

**Comment by bk138** [comment]
6964494b2a99e425867aed463d5e5244848a5947 introduced that.

**Comment by cshelton** [comment]
I figured it was something like that, so I didn't submit a change.  I think that means that instead of comparing to DEFAULT_HOTKEY, it needs to compare to something dynamic that is changed if XFCE is detected.
