### ISSUE TITLE
Bad Configuration Silently Dies

### ISSUE THREAD

**Issue by mikeperalta1** [bk138/gromit-mpx#118]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

**Describe the bug**
When custom user configuration file is present and the user launches gromit-mpx via desktop file (i.e., not via CLI), gromit-mpx silently dies with no indication of why.

**To Reproduce**
1. Create a bad custom config
2. Launch gromit-mpx from applications menu or similar (not CLI)
3. Gromit will simply fail to start

**Expected Behavior**
A popup window indicating the type of error with a link to documentation or similar.

**Desktop (please complete the following information):**
 - Ubuntu 20.10
 - Xorg version used: xorg/groovy,now 1:7.7+19ubuntu15 amd64 [installed]
 - Wayland version used: xwayland/groovy-updates,groovy-security,now 2:1.20.9-2ubuntu1.1 amd64 [installed,automatic]

 
**Additional context**
I just feel this would help new users who may not understand how to launch the program via CLI to see what is wrong, or realize the cause is a bad config file.

**Comment by bk138** [comment]
Please post an example bad config.

**Comment by mikeperalta1** [comment]
In this example, I copied the default file from ```/etc/gromit-mpx/gromit-mpx.cfg``` directly to ```~/.config/gromit-mpx.cfg```, and removed the first semicolon found. The altered line here is: ```"red Pen" = PEN (size=5 color="red")```

```
# Default gromit-mpx configuration 
# taken from  Totem's telestrator mode config
# added default entries

# Uncomment to set Hot key and/or Undo key to a custom value
# HOTKEY = "F9";
# UNDOKEY = "F8";

"red Pen" = PEN (size=5 color="red")
"blue Pen" = "red Pen" (color="blue");
"yellow Pen" = "red Pen" (color="yellow");
"green Marker" = PEN (size=6 color="green" arrowsize=1);

"Eraser" = ERASER (size = 75);

"default" = "red Pen";
"default"[SHIFT] = "blue Pen";
"default"[CONTROL] = "yellow Pen";
"default"[2] = "green Marker";
"default"[Button3] = "Eraser";
```

Then, launching from the Whisker Menu in XFCE (i.e., .desktop shortcut file), it silently fails.

Then, running from the command line:

```gromit-mpx```

I see the following message output:

```
Expected ";"
```
