### ISSUE TITLE
without compositor undo does not erase the drawn line but marks it black

### ISSUE THREAD

**Issue by goekce** [bk138/gromit-mpx#122]
**Describe the bug**
Without compositor, undo does not erase the red drawn line but only turns it to black.

**To Reproduce**
1. start gromit with empty config
2. press F9, draw a (red) line
3. press F8
4. see that the line is now black instead of being deleted.

**Expected Behavior**
Line is gone

**Screenshots**
![image](https://user-images.githubusercontent.com/18174744/109455775-9f66f400-7a57-11eb-908b-454d7b6b154b.png)

**Desktop (please complete the following information):**
 - OS and version: Archlinux
 - Xorg version used: 1.20.10
 - Wayland version used: n/a
 
**Additional context**
i3 without any compositor

**Comment by goekce** [comment]
After installing a compositor (`picom`), the problem is gone.

**Comment by bk138** [comment]
Does this happen with older Gromit-MPX versions as well?

**Comment by goekce** [comment]
This is my first time using Gromit-MPX, and I do not know.

**Comment by goekce** [comment]
sure!

**Comment by bk138** [comment]
Hi @goekce, did you find some time to try this out?

**Comment by goekce** [comment]
no :(
 is on my TODO list

**Comment by MarcinOrlowski** [comment]
Had the same issue with v1.4 on my KDE and found this ticket. I checked my system settings (in KDE `Hardware`->`Display and Monitors` -> `Compositor`) and figured out that my compositor managed to crash at some point and was disabled. Once I re-enabled it, erase started to work fine.
