### ISSUE TITLE
Cannot change toggle key

### ISSUE THREAD

**Issue by davidnsousa** [bk138/gromit-mpx#128]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

**Describe the bug**

Cannot set a permanent toggle key in xubuntu. Only temporarily when gromit is run with -k "Pause" for instance, or any other key.

**To Reproduce**

gromit-mpx -k "Pause"

the output is: 

Could not open /home/david/.config/gromit-mpx.cfg: No such file or directory
Supported backends: x11 wayland 
Using backend: x11
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.

I tried coping the gromit-mpx.cfg file from github, and tried again gromit-mpx -k "Pause" with ouptut

Expected name of Tool to define

**Desktop (please complete the following information):**
Xubuntu

**Comment by bk138** [comment]
You can ignore the log output about the config file. What's the output when you add `-d` to the commandline?

**Comment by davidnsousa** [comment]
with 

gromit-mpx -k -d "Pause"

i get

Unknown Option for Gromit-MPX startup: "Pause"
Please see the Gromit-MPX manpage for the correct usage

**Comment by bk138** [comment]
You can look up the version in aptitude or whatever package manager you use. You should use `-V` to display the version. You should not use `-d` in between `-k`and its argument. Please read the README.

**Comment by davidnsousa** [comment]
I tried 

gromit-mpx -V

it gives 

Unknown Option for Gromit-MPX startup: "-V"
Please see the Gromit-MPX manpage for the correct usage

But my gromit version is 1.3-1. I Checked it at the Synaptic Package manager.

**Comment by bk138** [comment]
Alright. Please read the last bits of [this README section](https://github.com/bk138/gromit-mpx#configuration): 1.3 does not support what you want to do. You can get a newer version via [FlatHub](https://flathub.org/apps/details/net.christianbeier.Gromit-MPX).
