### ISSUE TITLE
Error starting under wayland

### ISSUE THREAD

**Issue by ccakes** [bk138/gromit-mpx#132]
**Describe the bug**
App doesn't start on Arch Linux under Wayland (sway). Worth pointing out I don't have XWayland - the readme doesn't call out that it's required and the docs seem to suggest pure-Wayland support

```
$ gromit-mpx        
(gromit-mpx:7822): Gtk-WARNING **: 08:40:18.733: cannot open display: 

$ env | grep XDG
XDG_SEAT=seat0
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=sway
XDG_SESSION_CLASS=user
XDG_VTNR=1
XDG_SESSION_ID=1
XDG_RUNTIME_DIR=/run/user/1000
```

**To Reproduce**
1. `yay -S gromit-mpx`
2. `gromit-mpx`

**Desktop (please complete the following information):**
 - OS and version: Arch Linux
 - Xorg version used: N/A
 - Wayland version used: 
    ```
    pacman -Q | grep wayland
    egl-wayland 1.1.7-1
    wayland 1.19.0-1
    wayland-protocols 1.21-1
    ```
 

**Additional context**
I assume it's probably an issue with my config but having read through the readme and issues, I can't figure out what it would be :disappointed:

**Comment by bk138** [comment]
Yeah, it's a documentation issue. XWayland is required.
