### ISSUE TITLE
Blocks mouse clicks to other apps on wayland, needs hide-view to work

### ISSUE THREAD

**Issue by bk138** [bk138/gromit-mpx#136]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

**Describe the bug**

**To Reproduce**

One can click other windows always

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Debian 11
 - Xorg version used:
 - Wayland version used: Mutter 3.38
 

**Additional context**

**Comment by bk138** [comment]
56a6fb6e8530ca96def45c51d645900c3deee96d related?

**Comment by bk138** [comment]
This is new in GNOME 3.38, was not present on GNOME 3.32

**Comment by bk138** [comment]
@jocelyn Yeah, it seems an additional `gdk_window_invalidate_rect()` is needed to apply the input shape on newer GNOME versions at least.

**Comment by piater** [comment]
For me in sway, gromit-mpx v. 1.4.3 still does not pass mouse clicks. Other mouse-related events do not appear to be passed on either; focus-follows-mouse does not work as expected. Should I file a new issue?

**Comment by bk138** [comment]
> For me in sway, gromit-mpx v. 1.4.3 still does not pass mouse clicks. Other mouse-related events do not appear to be passed on either; focus-follows-mouse does not work as expected. Should I file a new issue?

Hmm, I guess so, but please make sure to include as much info as possible.
