### ISSUE TITLE
Introduction window is shown even if "Show again on startup" is unchecked or disabled

### ISSUE THREAD

**Issue by shreyasborole** [bk138/gromit-mpx#140]
**Description:**
Whenever the application is started, the introduction window is shown even if "Show again on startup" is unchecked.

**Expected Behavior:**
Whenever on Introduction window "Show again on startup" checkbox is unchecked the Introduction window should on be displayed on consecutive startup of application unless it is ticked/checked again.

**Desktop:**
 - OS and version: Garuda Linux (Arch-based)
 - Xorg version used: 1.20.13

**Comment by bk138** [comment]
This is a symptom of the missing functionality requested in #114. Let's track progress there.
