### ISSUE TITLE
Update the flatpak version to the runtime org.gnome.Platform/x86_64/40

### ISSUE THREAD

**Issue by codingepaduli** [bk138/gromit-mpx#141]
**Describe the bug**
Please, update the flatpak version to the runtime org.gnome.Platform/x86_64/40, as for
[ flathub / net.christianbeier.Gromit-MPX  Issue #1](https://github.com/flathub/net.christianbeier.Gromit-MPX/issues/1)

**To Reproduce**
Run `flatpak update` in order to update the Gromit-Mpx version installed.

**Expected Behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Debian 10
 - Xorg version used: 1:7.7+19
 - Wayland version used:
 

**Additional context**

**Comment by bbhtt** [comment]
I opened https://github.com/flathub/net.christianbeier.Gromit-MPX/pull/2, please test whenever the build gets posted. Thanks!

**Comment by bk138** [comment]
> I opened [flathub/net.christianbeier.Gromit-MPX#2](https://github.com/flathub/net.christianbeier.Gromit-MPX/pull/2), please test whenever the build gets posted. Thanks!

Thanks! Left some comments there. :-)
