### ISSUE TITLE
End and Home hotkeys fail under xfce (xubuntu 20.04)

### ISSUE THREAD

**Issue by jcbedacuk** [bk138/gromit-mpx#142]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

**Describe the bug**
Hotkeys are not grabbed - current master code puts up error dialog saying it can't grab them

**To Reproduce**
start gromit-mpx

**Expected Behavior**
works as advertised

**Desktop (please complete the following information):**
 - OS and version: Xubuntu 20.04
 - Xorg version used: (not relevant)
 - Wayland version used:
 

**Additional context**
Current version of xfwm4 in standard config also grabs ctrl-alt-Home and ctrl-alt-End for next and previous workspace. (It also grabs Insert and Delete, so those won't work either!) I resolved it by deleting the xfwm4 bindings - maybe that's all you can advise people to do?

**Comment by bk138** [comment]
We can surely change the defaults for XFCE, which exact version are you using and which key are "free"?

**Comment by jcbedacuk** [comment]
I don't think there are any free keys. xfwm4 version 4.14.1 (with some personal patches, but none relevant to hotkeys). F1-F12,Home,End are grabbed with ctrl-alt, and Insert,Delete are grabbed with alt.

**Comment by bk138** [comment]
OK Bad. What's the call to action?

**Comment by jcbedacuk** [comment]
Put something in the docs mentioning that users can clear the keybindings (Settings->Window Manager->Keyboard)? Have the dialog box tell people to consult the docs?
