### ISSUE TITLE
How do you actually draw and why is my 'o' key not working?

### ISSUE THREAD

**Issue by philippludwig** [bk138/gromit-mpx#144]
I am running gromit-mpx-1.4 under Gentoo, XFCE.

When I start it, my 'o' key stops working, but thats about it. How do I actually draw? Could not find anything about this in the instructions; it mentions the mouse, so naively I tried by clicking and dragging, but that does not work.

I tried the shortcuts and the options in the menu of the systray-element, but those do not seem to do anything.

**Comment by bk138** [comment]
Would you mind sharing your config? Normally, F9 is used as a drawing toggle, see https://github.com/bk138/gromit-mpx#how-to-use-it

**Comment by philippludwig** [comment]
I don’t have a config. Note that I am using XFCE.

```
Detected XFCE, changing default hot keys to 'Home' and 'End'
Could not open user config /home/philipp/.config/gromit-mpx.cfg: No such file or directory
Could not open system config /usr/local/etc/gromit-mpx/gromit-mpx.cfg: No such file or directory
No usable config found, leaving tools unconfigured!
```

**Comment by bk138** [comment]
Yeah, sorry for the confusion - on XFCE the drawing toggle is "Home". Also, if you built from source, do a `make install` so Gromit-MPX finds its resources. As for your 'o' key stopping working, it seems this gets grabbed, but I cannot tell why, there's nothing like this in the code IIRC.

**Comment by philippludwig** [comment]
Thanks for the reply. I did `make install`, that fixed the tray icon. So I played around with the `debug` option and found out that `o` is the undo key, while `u` is the draw hotkey. I tried remapping them in /usr/local/etc/gromit-mpx/gromit-mpx.cfg:

```
HOTKEY = "F12";
UNDOKEY = "F11";
```

But it seems that these settings are overridden by the XFCE detection:

```
Detected XFCE, changing default hot keys to 'Home' and 'End'
Using user config /home/philipp/.config/gromit-mpx.cfg
DEBUG: Ungrabbed all Devices.

(gromit-mpx:46302): libappindicator-CRITICAL **: 17:11:18.035: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
DEBUG: Grabbing hotkeys 'Home' and 'End' from keyboard '3' .
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.
DEBUG: Ungrabbed all Devices.
```

So I ran:

```
gromit-mpx -k Menu -u Control_R
```

And this actually worked! 

---

So I have a working setup now, but I don’t know if you want to debug this behavior. In that case I would be happy to supply any additional information or try things. Otherwise, thank you for your time!

**Comment by bk138** [comment]
> Thanks for the reply. I did `make install`, that fixed the tray icon. So I played around with the `debug` option and found out that `o` is the undo key, while `u` is the draw hotkey.

Hmm, something's strange with your setup: Don't know where 'o' and 'u' are set, this is definitely not in the source. Are you using a git checkout or the Gentoo-modified source? 

> But it seems that these settings are overridden by the XFCE detection:

The XFCE detection changes the _defaults _, but if there is user config, that one is used.

You might want to try with a vanilla checkout from GitHub, otherwise feel free to close!

**Comment by philippludwig** [comment]
The version in the gentoo repository is tagged 2004, which would I consider ancient. I am using version 1.4, downloaded here from github:

```
gromit-mpx --version
Detected XFCE, changing default hot keys to 'Home' and 'End'
Gromit-MPX 1.4
```

Anyway, I tried looking at the source code to figure out what is going on, but I did not spot anything obvious. I will close this issue then, the command line arguments work good enough.
