### ISSUE TITLE
Allow toggling on/off for specific xinput device

### ISSUE THREAD

**Issue by dessaya** [bk138/gromit-mpx#145]
Currently it's very difficult to make multiple xinput cursors to work with a wacom tablet. After reattaching the wacom pen input device to xinput's `two` master pointer, I have no way to configure a button to toggle gromit-mpx for that cursor. I only have one keyboard, and I want it associated with my mouse.

A possible solution would be to somehow allow specifying a specific xinput device in the configuration. Something like:

```
HOTKEY[21] = "F9";
```

Or when using the command line:

```
gromit-mpx --toggle --device-id=21
```

**Comment by bk138** [comment]
That functionality already exists but was not documented. Did this now.
