### ISSUE TITLE
GNOME systray with gnome-shell-extension-appindicator does not toggle when under X11

### ISSUE THREAD

**Issue by franckgaga** [bk138/gromit-mpx#149]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

**Describe the bug**
The "Toggle Painting" function of the systray menu does not works in Pop!_OS 21.10 (probably also in Ubuntu 21.10). Everything else in the systray works and F9 shortcut does works. Nothing appear in the console at mouseclick if I run it with `gromit-mpx -d`

**To Reproduce**
1. Go to gromit-mpx systray
2. Click on 'Toggle Painting'
3. Nothing happen

**Expected Behavior**
The menu should activate drawing on the screen.

**Desktop (please complete the following information):**
 - OS and version: Pop!_OS 21.01
 - Xorg version used: X.Org X Server 1.20.13
 - Wayland version used:
 

**Additional context**
This error is printed in the console at gromit-mpx startup :
```
Could not open user config /home/francis/.config/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Using system config /etc/gromit-mpx/gromit-mpx.cfg

(gromit-mpx:11501): libayatana-appindicator-CRITICAL **: 13:30:07.049: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.

(gromit-mpx:11501): libayatana-appindicator-CRITICAL **: 13:30:07.049: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed

**Comment by bk138** [comment]
Hi, which version of Gromit-MPX are you using? Which desktop environment is this on? We had something similar with KDE...

**Comment by franckgaga** [comment]
gromit-mpx v1.4
Pop!_OS 21.10 is using Gnome v40.4.0

**Comment by bk138** [comment]
Alright, thanks! Do you have info on how the systray is implemented on Pop? Via a gnome-shell-extension? If so, which one? (I use TopIconsFix for example which works with the toggle entry...)

**Comment by franckgaga** [comment]
It's https://github.com/ubuntu/gnome-shell-extension-appindicator
with the last version (v41)
You are right with TopIconsFix, but it break the menu of my other systray icons

**Comment by bk138** [comment]
Yeah that extensions more or less replicates KDE behavior without us being able to autodetect it like [so](https://github.com/bk138/gromit-mpx/commit/b95ee61f49fbf9c8083fd754d84f6c4e91d2fda1). From a systray perspective, you've got KDE while we're detecting GNOME...  

No good idea from my side for now on how to handle this :-/

**Comment by bk138** [comment]
Maybe:
* https://wiki.gnome.org/Initiatives/StatusIconMigration/Guidelines#Checking_if_the_environment_supports_status_icons

**Comment by bk138** [comment]
@franckgaga can you try and run `dbus-send --session --print-reply --dest=org.freedesktop.DBus / org.freedesktop.DBus.GetConnectionUnixProcessID string:org.kde.StatusNotifierWatcher` ?

For my system, this yields: `Error org.freedesktop.DBus.Error.NameHasNoOwner: Could not get PID of name 'org.kde.StatusNotifierWatcher': no such name` as expected

**Comment by franckgaga** [comment]
Seems like a good solution, it returns this :
`method return time=1643911285.754507 sender=org.freedesktop.DBus -> destination=:1.250 serial=3 reply_serial=2
   uint32 3676`

**Comment by bk138** [comment]
https://titanwolf.org/Network/Articles/Article?AID=97db5b28-d729-431f-8026-31d57b928c9d has a C impl.

**Comment by bk138** [comment]
@franckgaga If you can, please double-check https://github.com/bk138/gromit-mpx/commit/de31837c0af97c3dd9f1f891ccd2dfa4265e0094, it should very much fix the issue.

**Comment by franckgaga** [comment]
@bk138 Do you want me to compile and test it ? I'm trying to compile it but after `cmake ..` i get the following error 
```
-- Checking for module 'ayatana-appindicator3-0.1 >= 0.5'
--   No package 'ayatana-appindicator3-0.1' found
-- Checking for module 'appindicator3-0.1 >= 0.4.92'
--   No package 'appindicator3-0.1' found
CMake Error at /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  CMakeLists.txt:29 (pkg_check_modules)
```
which package should i install ?

**Comment by bk138** [comment]
That'd be nice! You can try with `sudo apt-get build-dep gromit-mpx` - this should install all needed dependencies...

**Comment by franckgaga** [comment]
@bk138  It does not fix the issue. There is this message in the terminal at startup 
```
(gromit-mpx:32128): libayatana-appindicator-CRITICAL **: 17:51:02.652: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.

(gromit-mpx:32128): libayatana-appindicator-CRITICAL **: 17:51:02.653: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
```
and this message when I click "Toggle Painting" 
```
Error grabbing Device 'Virtual core pointer' while grabbing all, ignoring.
```

**Comment by bk138** [comment]
Mh, can you start with `-d`?

**Comment by bk138** [comment]
> and this message when I click "Toggle Painting"
> 
> ```
> Error grabbing Device 'Virtual core pointer' while grabbing all, ignoring.
> ```

This is new after the commit in question, right? Can you try with `-d` added to the cmdline?

**Comment by franckgaga** [comment]
> > and this message when I click "Toggle Painting"
> > ```
> > Error grabbing Device 'Virtual core pointer' while grabbing all, ignoring.
> > ```
> 
> This is new after the commit in question, right? Can you try with `-d` added to the cmdline?

@bk138 Yes this is new with the `de31837`commit. Also new with this commit : the icon changes to this after i clicked Toggle :
![image](https://user-images.githubusercontent.com/34136215/152809040-60ecca51-6fa4-4d0a-b2a7-add1d5fb518b.png)

With `-d` I get this at startup
```
DEBUG: Ungrabbed all Devices.

(gromit-mpx:39582): libayatana-appindicator-CRITICAL **: 09:40:23.377: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
DEBUG: Grabbing hotkeys 'F9' and 'F8' from keyboard '3' .
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.
DEBUG: Ungrabbed all Devices.

(gromit-mpx:39582): libayatana-appindicator-CRITICAL **: 09:40:23.378: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
DEBUG: Hiding window.
DEBUG: org.kde.StatusNotifierWatcher is owned
DEBUG: got configure event
```
and this after i click "Toggle"
```
DEBUG: Showing window.
Error grabbing Device 'Virtual core pointer' while grabbing all, ignoring.
DEBUG: Grabbed all Devices.
DEBUG: got draw event
```

**Comment by bk138** [comment]
The icon is not shown because the app resources are not installed after the customt build, that can be safely ignored.

`DEBUG: org.kde.StatusNotifierWatcher is owned` is actually what we want and also the line `DEBUG: Grabbed all Devices` tells us that it worked: Before de31837c0af97c3dd9f1f891ccd2dfa4265e0094, it would try to deduce the device that clicked "toggle" from the click and just grab that, after de31837c0af97c3dd9f1f891ccd2dfa4265e0094 it simply grabs all. 

Super strange in your case that it behaves that way.

* can you post the debug output for the hotkey toggle case?
* and the output of `xinput list`

And thanks for going through all this, It'll also help other users!

**Comment by franckgaga** [comment]
@bk138 for the hotkey `F9`, I get 
```
DEBUG: Received hotkey press from device 'Virtual core keyboard'
DEBUG: Showing window.
DEBUG: Grabbed Device 'Virtual core pointer'.
DEBUG: got draw event
```
and `xinput list`
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ASUE140A:00 04F3:3134 Touchpad          	id=11	[slave  pointer  (2)]
⎜   ↳ ASUE140A:00 04F3:3134 Mouse             	id=13	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	https://github.com/bk138/gromit-mpx/issues/149#id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ USB2.0 HD UVC WebCam: USB2.0 HD         	id=9	[slave  keyboard (3)]
    ↳ USB2.0 HD UVC WebCam: USB2.0 IR         	id=10	[slave  keyboard (3)]
    ↳ ASUE140A:00 04F3:3134 Keyboard          	id=12	[slave  keyboard (3)]
    ↳ Asus WMI hotkeys                        	id=14	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=15	[slave  keyboard (3)]
    ↳ asus_numpad                             	id=16	[slave  keyboard (3)]
```
no problem, indeed there is probably many users that relies on gnome-shell-extension-appindicator

**Comment by bk138** [comment]
What happens if you do a `./gromit-mpx -t` from within the build dir when you have an already running gromit-mpx instance? Does the main instance also show `Error grabbing Device 'Virtual core pointer' while grabbing all, ignoring.`? Does the cursor change?

**Comment by franckgaga** [comment]
It does toggle, the cursor change and I can draw on the screen. The console of the main instance prints
```
DEBUG: mainapp got toggle id '-1' back from client.
DEBUG: Showing window.
DEBUG: Grabbed all Devices.
DEBUG: got configure event
DEBUG: got draw event
```
thus no error

**Comment by bk138** [comment]
Alright, I can now repro with https://github.com/ubuntu/gnome-shell-extension-appindicator, but only under X11, not under Wayland. It seems https://github.com/ubuntu/gnome-shell-extension-appindicator was a step in the right direction, but not enough.

**Comment by franckgaga** [comment]
@bk138 Thanks for the fix! The typical wait/sleep workaround, we all need the sometimes XD

**Comment by bk138** [comment]
> @bk138 Thanks for the fix! The typical wait/sleep workaround, we all need them sometimes XD

Yeah, not happy about this at all, but it does the trick... 🤞
