### ISSUE TITLE
Setting minimal cursor size

### ISSUE THREAD

**Issue by wavexx** [bk138/gromit-mpx#15]
I'm trying to use gromit-mpx to annotate some live presentations. I tried ardesia, but it's quite a hefty package for the basic features I need.

gromit-mpx works nicely, but still comes short on a few things.

With a wacom tablet, it looks like a setting for minimal cursor size should be present. If I set size=5 on a cursor, I need to press quite hard to get a thin line to be visible. To get a decent feel I've set size=25, but the maximal thickness is now actually too big.

There should be a minsize setting, so that I can control the dynamic range of the stylus and ensure that any stroke is at least 1/2 pixels.

**Comment by barak** [comment]
Yes.

I suppose the right thing to do is to have handful of parameters to control the pressure/size relationship.
The first thing that comes to mind is a set of five parameters: minimum size/pressure, maximum size/pressure and a gamma parameter as in brightness to control how it ramps up.

Patches welcome!

**Comment by wavexx** [comment]
For a simple sketching application, just ensuring a minimal cursor size would do it. Especially considering you can already tweak the response curve using xsetwacom.

**Comment by bk138** [comment]
Guess this is fixed with https://github.com/bk138/gromit-mpx/commit/bb51710f4f3371480030ae7f9d6da91a1f37e6ea? Thanks!
