### ISSUE TITLE
Could not open user config /home/user/.config/gromit-mpx.cfg: File or folder not found

### ISSUE THREAD

**Issue by ericschdt** [bk138/gromit-mpx#156]
**Describe the bug**

```
gromit-mpx --key F8 --undo-key F9
Could not open user config /home/user/.config/gromit-mpx.cfg: File or folder not found
Using system config /etc/gromit-mpx/gromit-mpx.cfg
```

There's however a
```
~/.config/gromit-mpx.ini 
```

Is that a packaging issue?

**Environment (please complete the following information):**
 - Gromit-MPX version: gromit-mpx-1.4-1.10
 - Flatpak or Distribution-package or Built-from-source: distribtion repo 
 - OS and version: openSUSE TW
 - Desktop Environment and version: KDE Plasma 5.24.5
 - X11 or Wayland session: Wayland

**Comment by bk138** [comment]
No, there's two sorts of config files actually:
* the "old" .cfg files which are user-written
* the "new-style" .ini file which is just a backing store for things that were changed in the UI.

So what you see means: you have UI settings stored in `~/.config/gromit-mpx.ini` but no user-written config in `~/.config/gromit-mpx.cfg` (yet).
