### ISSUE TITLE
Cursor switching with wacom styluses doesn't work

### ISSUE THREAD

**Issue by wavexx** [bk138/gromit-mpx#16]
Styluses normally have two buttons on the side (button 1/2), but I cannot make them work.
I think this is due to the fact that drawing by itself normally triggers button 0, and erasing triggers button 3.

**Comment by bk138** [comment]
Mhh I don't have a wacom. So those things have how many sensors?

**Comment by wavexx** [comment]
These styluses usually have 4 axes (x/y, pressure and eraser) and two extra buttons on the pen itself. The intuos tablet can also record tilt (angle and azimuth) and the "art pens" also have rotation around z. The tablet itself has usually 2 to 8 extra buttons.

Pressing on the stylus usually triggers button 0 after a certain non-zero threshold, which stays on until pressure is removed. Likewise for the eraser. I guess for compatibility with programs built for mice.

**Comment by wavexx** [comment]
I was also thinking that it would make sense to have actions for button presses, like button1="switch to next pen" and button2="switch color". Holding down these buttons is not comfortable.

**Comment by bk138** [comment]
I see. If you want to come up with something nice, feel free to file a PR! I'd happily do a new release soonish.

**Comment by wavexx** [comment]
I don't know when I'm going to do it, I'm doing this in random free time. I recently started doing some teaching, thus I've started to try/modify a couple of projects to see what fits best.

I have to say, bringing one of those tablets around is a bit cumbersome :/

I tried fingering around with some touch-sensitive screen, but it's honestly even crappier than using a mouse (I cannot see what I'm annotating, it's still *very* imprecise for text).

Can I ask what do you use gromit for?

**Comment by bk138** [comment]
Well I created it as one integral part of my thesis, a networked multi-user on-screen collab tool. This paper http://www.thinkmind.org/download.php?articleid=colla_2012_3_40_50040 gives an overview ;-)

**Comment by bk138** [comment]
Side button down gives me
```
DEBUG: Device 'Wacom Intuos S 2 Pen stylus': Button 2 Down at (x,y)=(588,47 : 421,04)
DEBUG: Looking up context Wacom Intuos S 2 Pen stylus|@0
DEBUG: Default context default|@0 set
DEBUG: Looking up context Wacom Intuos S 2 Pen stylus|@0
DEBUG: Default context default|@0 set
DEBUG: Looking up context Wacom Intuos S 2 Pen stylus|B0
DEBUG: Default context default|B0 set
DEBUG: Setting cursor 0x5605f6958100
DEBUG: Snapping undo buffer 3.
DEBUG: draw line from 588 421 to 588 421
DEBUG: got draw event
DEBUG: Device 'Wacom Intuos S 2 Pen stylus': Button 2 Up at (x,y)=(593,01 : 419,00)
DEBUG: Looking up context Wacom Intuos S 2 Pen stylus|@0
DEBUG: Default context default|@0 set
DEBUG: Setting cursor 0x5605f6958100
```

and - for the upper button side:

```DEBUG: Device 'Wacom Intuos S 2 Pen stylus': Button 3 Down at (x,y)=(558,03 : 359,32)
DEBUG: Looking up context Wacom Intuos S 2 Pen stylus|@0
DEBUG: Default context default|@0 set
DEBUG: Looking up context Wacom Intuos S 2 Pen stylus|@0
DEBUG: Default context default|@0 set
DEBUG: Looking up context Wacom Intuos S 2 Pen stylus|@0
DEBUG: Default context default|@0 set
DEBUG: Looking up context Wacom Intuos S 2 Pen stylus|D0
DEBUG: Default context default|D0 set
DEBUG: Setting cursor 0x5561928ad940
DEBUG: Snapping undo buffer 1.
DEBUG: draw line from 558 359 to 558 359
DEBUG: got draw event
DEBUG: Device 'Wacom Intuos S 2 Pen stylus': Button 3 Up at (x,y)=(558,03 : 358,75)
DEBUG: Looking up context Wacom Intuos S 2 Pen stylus|@0
DEBUG: Default context default|@0 set
DEBUG: Setting cursor 0x5561928ad900
```

**Comment by wavexx** [comment]
I have a Bamboo, Intuos Pro and an X1 Yoga (with a Walcom stylus) if you need any specific testing.
They all behave in the same way in terms of button mapping, with the exception that the Yoga pen has no eraser and very crappy pressure resolution.

I'm currently using the ``libinput`` Xorg driver, which since last year seems to work decently.

**Comment by abrasive** [comment]
There are two ways you could eg. erase with a side button: either hold the button and then press down to erase, or just hold the button and wave the stylus over the area you need.
The former generates buttonN + button1 + pressure, while the latter generates only buttonN with zero pressure.


Personally I'd prefer the latter for erasing/recolouring (less fatiguing), and it should be easier to implement. As a test I've bodged in a patch like
```
    if (pressure == 0)
        pressure = 1;
```
This messes up light pressure drawing with the normal pen, but it does make the side button work as an eraser.

**Comment by abrasive** [comment]
I can see a couple of ways one might approach this, what do you think?

One could allow tools to have a fixed size (or minimum size), allowing zero pressure drawing.

And to allow side button + stylus pressure erasing like this, one would have to change the buttons priority logic so that button1 does not dominate other configured buttons. That's a bigger change, no?

**Comment by wavexx** [comment]
More importantly it'd definitely use one of the side buttons to switch the active pen to the next one.

**Comment by grevius5** [comment]
i have a wacom bamboo and I have the same issue, i can write, but when i press a button for eraser i see the circle, but when i tap on the pad it use the pen and not the eraser

**Comment by bk138** [comment]
General update: issues with Gromit-MPX can now be funded at https://issuehunt.io/r/bk138/gromit-mpx

**Comment by Maralai** [comment]
I have recently tried the original gromit application and it appeared to work with my side button eraser, although it was creating lines between the last pen up position and the next pen down position rendering it useless for my device. I am playing with your app and am finding it render very nice lines on the screen that feel fluid however I cannot use my pen's eraser like I could with gromit. Is this a configuration issue?

**Comment by bk138** [comment]
Might be. Or a coding issue. The code has changed/evolved from the original gromit quite a bit.

**Comment by Maralai** [comment]
The eraser is working as expected when tested using `xinput --test 22` when the button is pressed... trying to work through your readme and see if I can assign that id to an eraser tool...

**Comment by Maralai** [comment]
I can't seem to figure out how to assign:
`"default"[Button3] = "Eraser";`
to:
`"ELAN Touchscreen Eraser (0)"[Button3] = "Eraser";`

How to use the output from `xinput --list` to specify what is listened to? I feel like if I can do this I can have it only listen to the pen, solving my palm issue and have it listen to the eraser and run the erase function. Your assistance is appreciated and certainly worth a beer or coffee.

**Comment by Maralai** [comment]
I got it! I had the [Button3] field where it didn't belong:
In the configuration changing:
`"default"[Button] = "Eraser";` to 
`"ELAN Touchscreen Eraser (0)" = "Eraser";`
works flawlessly.

**Comment by bk138** [comment]
Nice! Can you please post your complete config?

**Comment by Maralai** [comment]
`# Default gromit-mpx configuration 
# taken from  Totem's telestrator mode config
# added default entries

"red Pen" = PEN (size=5 color="red");				
"blue Pen" = "red Pen" (color="blue");				
"yellow Pen" = "red Pen" (color="yellow" size=10);
"no Pen" = PEN (size=0);		
									
"Eraser" = ERASER (size = 75);					

"default" = "no Pen";									
"ELAN Touchscreen Pen (0)" = "red Pen";						
"ELAN Touchscreen Pen (0)"[SHIFT] = "blue Pen";					
"ELAN Touchscreen Pen (0)"[CONTROL] = "yellow Pen";		
"ELAN Touchscreen Eraser (0)" = "Eraser";
`

**Comment by bk138** [comment]
> I hope you got my coffee/beer money, cheers!

Yes, just received a mail! Thanks a lot, that'll finance some 🍻!
