### ISSUE TITLE
Dark mode in the Introduction and About windows not working for DEs other than GNOME

### ISSUE THREAD

**Issue by mmahmoudian** [bk138/gromit-mpx#169]
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

First and foremost, thank you for this handy tool. It is a bonus that it is available as Flatpak.

**Is your feature request related to a problem? Please describe.**
I tend to forget the keybindings and therefore I have to keep this window open 👇🏼 which in a desktop with a dark theme causes lots of distraction and eyestrain
![image](https://user-images.githubusercontent.com/390889/193880418-493ba39f-e104-4218-87eb-f6a681cd7f79.png)

**Describe the solution you'd like**
It would be nice if:
there is a toggle button somewhere in the window to be used for toggling dark mode. It would be extra nice if it can remember the last state as well.

**Describe alternatives you've considered**
Gromit does not have config, but if it had, this could go in the that file.

**Additional context**
--Not Applicable--

**Comment by bk138** [comment]
As Gromit-MPX uses GTK3, you can simply [use a GTK theme switcher and select a dark theme](https://www.ecosia.org/search?tt=mzl&q=change%20gtk%20theme). Does this solve your issue?

**Comment by mmahmoudian** [comment]
Well, I have appiled the theme to GTK and all software I have are respecting it regardless of being installed via official distro repo of Flatpak. For instance in the following image I have opened Meld, pamac, and Flatseal. All are GTK, the first two are installed from official Manjaro repo, and Flatseal is installed via Flatpak.

![image](https://user-images.githubusercontent.com/390889/193897060-320de861-430d-4d5a-a3a5-f20a61918354.png)


For some reason Gromit does not follow the theme. I wonder if it is a bug (e.g during packaging in Flatpak) or it is kinda hard-coded. Can it be that it uses some old GTK versions?

**Comment by mmahmoudian** [comment]
I have installed via Flatpak. This screenshot is from another Manjaro KDE machine in which the same issue persists. On both machines I have the latest Gromit and latest runtimes from stable branch of Flathub, and in both I have set dark theme for GTK

![image](https://user-images.githubusercontent.com/390889/194040964-215f011b-ce79-4b99-a0be-1bab559ee476.png)

**Comment by bk138** [comment]
Thanks for your help offer - could you maybe try and install a repo package or build from source? I'd like to rule out the flatpak packaging...

**Comment by bk138** [comment]
@mmahmoudian I did some testing myself and here's what I found out:

* installed the flatpak from https://flathub.org/apps/details/net.christianbeier.Gromit-MPX
* changed theme to "Adwaita-dark" via gnome-tweak-tool
* About window of Gromit-MPX is dark ✅

One hint: `flatpak list | grep theme` gives me `Adwaita dark GTK theme	org.gtk.Gtk3theme.Adwaita-dark		3.22	flathub	system`, amongst others, so this might not be installed for you?

**Comment by mmahmoudian** [comment]
> changed theme to "Adwaita-dark" via gnome-tweak-tool

Is your host machine Gnome? Because I'm on KDE (both machines) and I am using the "Breath-Dark" GTK theme that is shipped with my KDE (to have the same exact colors as I have with my Qt applications):

![image](https://user-images.githubusercontent.com/390889/194054192-a0b5d4d5-0ebf-4e8f-8de0-1c373264f6e9.png)

but I have already the following installed (not installed today, but installed 
![image](https://user-images.githubusercontent.com/390889/194054498-2d486ee2-106e-4480-abad-73522e05204a.png)

Here is a bit more info:

```console
❯  flatpak list --show-details | grep "theme"
Breeze GTK theme	Breeze GTK theme matching the KDE Breeze theme	org.gtk.Gtk3theme.Breeze	5.25.5	3.22	x86_64	flathub	system	org.gtk.Gtk3theme.Breeze/x86_64/3.22	2b52c4d5913c	-	636.4 kB	system,runtime
Adwaita theme	Adwaita widget theme matching the GNOME adwaita theme	org.kde.KStyle.Adwaita		5.15-21.08	x86_64	flathub	system	org.kde.KStyle.Adwaita/x86_64/5.15-21.08	811d090059b2	-	16.3 MB	system,runtime
```

One thing to mention is that all other GTK-based software (flatpak or not) are correctly accepting the GTK theme. The only outlier is Gromit as far as I can tell.

> could you maybe try and install a repo package or build from source?

Gromit-MPX is not offered in Arch official repos, but I will try compile it myself and report back

**Comment by bk138** [comment]
Yes, I'm running GNOME. 

Is there a Breath-Dark flatpak you might be able to install?

**Comment by mmahmoudian** [comment]
> Is there a Breath-Dark flatpak you might be able to install?

No I checked the moment you shared that link:

```console
❯  flatpak remote-ls flathub | grep "org.gtk.Gtk3theme" | grep -i "breath" | wc -l
0
```

**Comment by bk138** [comment]
@mmahmoudian can you maybe try with another theme and/or desktop environment?

**Comment by bk138** [comment]
Closing for now, please feel free to post new info once available.
