### ISSUE TITLE
Documentation: Color switching for XP Pen

### ISSUE THREAD

**Issue by jahagirdar** [bk138/gromit-mpx#170]
From the man page it is not clear how to implement color switching with XP-Pen Tablet.
My configuration file is
```
"red Pen" = PEN (size=5 color="red");
"blue Pen" ="red Pen" (color="blue");
 
"default"= "red Pen";
"default"[SHIFT]= "blue Pen";
"10 inch PenTablet Pen (0)"  = "red Pen";
"10 inch PenTablet Pen (0)"[SHIFT]  = "blue Pen";
```
I am executing the following commands in my terminal.

```
xinput --create-master mpx 
xinput --reattach 16 18
gromit-mpx
gromit-mpx --toggle 0
```

My expectation was hitting the shift key and scribbling with the tablet pen will change color. it does not. 
Looking at the bug report I can see other are using their tablet with colors. but there was no reference instruction or configuration file :(

**Comment by bk138** [comment]
Hi @jahagirdar, your expectation is right, it _should_ work. I can only offer some ideas why it would not:

* Is the keyboard you're pressing Shift on paired with the MPX master device that is the pen?
* You might also be running into #106 when running under Wayland.

**Comment by jahagirdar** [comment]
The Physical keyboard is on a different master... "Virtual core keyboard"

I checked the keys on XP-Pen tablet with xev. They generated the following code
Key1:
Key2:
Key3: 'b'
Key4: 'e'
Key5: '^Z'
Key6: '^S'
Key7: '^Z'
Key8: '^Y'
Can this be used in the configuration file to change the pen behavior?

**Comment by itcultus** [comment]
This is the configuration I use with my XP-PEN and works relatively OK. 

```
"red Pen" = PEN (size=4 color="red");
"blue Pen" = "red Pen" (color="#4682B4");
"yellow Pen" = "red Pen" (color="#FE8B1B");
"green Marker" = PEN (size=5 color="green" arrowsize=2);

"Eraser" = ERASER (size = 80);

"XP-PEN STYLUS Pen (0)" = "red Pen";
"XP-PEN ERASER Eraser (0)" = "Eraser";

"default" = "red Pen";
"default"[SHIFT] = "blue Pen";
"default"[CONTROL] = "green Marker";
"default"[META] = "yellow Pen";
"default"[Button3] = "Eraser";
```

**Comment by bk138** [comment]
OK, closing then.
