### ISSUE TITLE
Intro window pops up on startup

### ISSUE THREAD

**Issue by nailuj29** [bk138/gromit-mpx#176]
**Describe the bug**

Whenever I restart my computer, the intro window pops up, regardless of which option I select

**To Reproduce**

1. Install gromit-mpx from AUR
2. Uncheck "show again on startup"
3. Restart computer

**Expected Behavior**

Window does not appear

**Screenshots**

**Environment (please complete the following information):**
 - Gromit-MPX version: 1.4.3
 - Flatpak or Distribution-package or Built-from-source: Distro Package
 - OS and version: Arch Linux 6.1.8
 - Desktop Environment and version: GNOME 43.2
 - X11 or Wayland session: x11
 

**Additional context**

**Comment by bk138** [comment]
Thanks for your report! This is actually #114, please subscribe there.
