### ISSUE TITLE
Is it possible to disable pressure sensitivity for X230T ( Wacom stylus) ?

### ISSUE THREAD

**Issue by maxchendt** [bk138/gromit-mpx#18]
gromit-mpx is great!

In Ubuntu, the default short cut key is Pause, I recently work it out on my X230T, and the key press is Fn+P.

When I am drawing something, the pressure sensitivity is nice in gromit-mpx.  However, when I am teaching and writing some formulas, I like to turn off the pressure sensitivity, as the Annotate plugin of compiz, who treats the Wacom stylus as a mouse. 

Once I use Annotate plugin of compiz in Ubuntu (12.04, 14.04+xfce, 14.04+mate1.82) in teaching, for examples
https://www.youtube.com/watch?v=4yBW1tOx9p0
https://www.youtube.com/playlist?list=PLVmaHFXy6tldlu5ZKR-3M89dP-YicRPLl

gromit-mpx provides the flexibility to change color, this point is much better than Annotate plugin of Compiz. If there is a way to disable the pressure sensitivity, that will be super.

**Comment by bk138** [comment]
You want to do that on the fly? That's not implemented as of now. But what you can try is setting size and minsize to the same value in the config file as of bb51710f4f3371480030ae7f9d6da91a1f37e6ea.

**Comment by maxchendt** [comment]
Thanks so much!
It seems that I should set the *minwidth* and then compile the source file? If so, I will try it later.
Here are some of my suggestions (no need to recompile for user side)
1 command line to set "gromit-mpx --minsize 7",  to control a running process
2 read from gromit-mpx.cfg, e.g.,  "red Pen" = PEN (size=7 color="red" minsize=7);
3 provide menu/dialog to set the related parameter, and to active and deactive
(I think that the above are ordered by increasing ease for user, but increasing workload to implement.)

**Comment by bk138** [comment]
No you don't need to recompile! Config file! ;-)

**Comment by maxchendt** [comment]
Thanks so much!
I record a screen video: https://youtu.be/DxJk3K3iJqE , sorry for my ugly spoken English.
