### ISSUE TITLE
Gromit-MPX replaces `~/.config/gromit-mpx.ini` 

### ISSUE THREAD

**Issue by MathiasSven** [bk138/gromit-mpx#182]
**Describe the bug**
Gromit-MPX replaces `~/.config/gromit-mpx.ini`, this gets in the way of config managing software like [Home-Manager](https://github.com/nix-community/home-manager) from being able to operate properly. 

**Expected Behavior**
If Gromit-MPX is to write to that file, and it is unable to due to it being read-only, it should fail the operation, not replace file.   

**Environment (please complete the following information):**
 - Gromit-MPX version: 1.4.3
 - OS and version: NixOS

**Comment by bk138** [comment]
Happy to merge a PR.
