### ISSUE TITLE
Can't bind draw key to a key with modifiers

### ISSUE THREAD

**Issue by gepbird** [bk138/gromit-mpx#184]
**Describe the bug**
Binding the draw key to keys with "advanced" modifiers doesn't work (key is not recognized or key does nothing).

**To Reproduce**
Launching Gromit-MPX with `--key F8` for example works as expected: the program starts and I can use the F8 key to go into drawing mode.
With arguments `--key Control_R`, the program starts, but pressing Control+R doesn't go into draw mode.
With arguments `--key Control_T`, the program crashes: `cannot find the key "Control_T"`.

**Expected Behavior**
The user should be able to bind the draw or the undo key to any combination of modifiers + a key.

**Environment (please complete the following information):**
 - Gromit-MPX version: 1.5.1
 - Flatpak or Distribution-package or Built-from-source: built from source by distro
 - OS and version: NixOS
 - Desktop Environment and version: dwm-6.4
 - X11 or Wayland session: X11
 

**Additional context**
After digging around for a while in the code, looks like only keys in [gdkkeysyms.h](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/gdkkeysyms.h) are supported which is unfortunate, because it is very limited. (when searching for Control, why is there only Control_L and Control_R?). I'd love to see [x11 keysyms](https://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h) support, but I understand it's not an easy change.

**Comment by bk138** [comment]
You're right, only keys from gdkeysyms.h are supported. Btw, `Control_R` does not mean Ctrl+R, it means "right control key".

**Comment by gepbird** [comment]
Thanks for clarifying Control_R.

I didn't see that an already running Gromit-MPX process can be controlled by running `gromit-mpx --toggle`, this can be easily mapped to any key since it's just a shell command.
