### ISSUE TITLE
Possible parentheses missing in code in on_device_removed and on_device_added, in callbacks.c

### ISSUE THREAD

**Issue by pascal-niklaus** [bk138/gromit-mpx#188]
I did not notice any actual misbehavior, but the following code seems odd:

callbacks.c: 578:
```
  if(!gdk_device_get_device_type(device) == GDK_DEVICE_TYPE_MASTER
     || gdk_device_get_n_axes(device) < 2)
    return;
```

same again on line 664 (on_device_added).

This would evaluate to TRUE when gdk_device_get_device_type returns values > 0, since GDK_DEVICE_TYPE_MASTER is 0.

If this is correct, maybe better write as `gdk_device_get_device_type(device) != GDK_DEVICE_TYPE_MASTER)` or
`!(gdk_device_get_device_type(device) == GDK_DEVICE_TYPE_MASTER)`.

**Comment by bk138** [comment]
That's right, would you like to open a PR changing this to `!=` ?
