### ISSUE TITLE
Gromit-MPX no longer works on Fedora Rawhide

### ISSUE THREAD

**Issue by russel** [bk138/gromit-mpx#19]
Whilst Debian packages Gromit-MPX, Fedora appears not to. So I have been using Debian packages, but compiling from this repository for Fedora. Until last week things seemed fine. A change to Fedora Rawhide between Wednesday 2015-06-24 and Saturday 2015-06-27 has made Gromit-MPX fail to pick up the WACOM and to Segfault on first signal from the WACOM after pressing F9. This is not a kernel thing per se as I just tried with an old kernel and got the same behaviour.

|> gromit-mpx 
Supported backends: x11 wayland 
Using backend: x11
Enabled Device 0: "Virtual core pointer", (Type: 0)
Enabled Device 1: "TPPS/2 IBM TrackPoint", (Type: 0)
Enabled Device 2: "SynPS/2 Synaptics TouchPad", (Type: 6)
Enabled Device 3: "ELAN Touchscreen", (Type: 5)
Enabled Device 4: "Virtual core XTEST pointer", (Type: 0)
Now 5 enabled devices.
Segmentation fault (core dumped)

|> gdb gromit-mpx 
GNU gdb (GDB) Fedora 7.9.50.20150531-3.fc23
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gromit-mpx...done.
gdb>r
Starting program: /home/russel/Built/bin/gromit-mpx 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.21.90-17.fc23.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe4e90700 (LWP 3532)]
[New Thread 0x7fffdffff700 (LWP 3533)]
Supported backends: x11 wayland 
Using backend: x11
Enabled Device 0: "Virtual core pointer", (Type: 0)
Enabled Device 1: "TPPS/2 IBM TrackPoint", (Type: 0)
Enabled Device 2: "SynPS/2 Synaptics TouchPad", (Type: 6)
Enabled Device 3: "ELAN Touchscreen", (Type: 5)
Enabled Device 4: "Virtual core XTEST pointer", (Type: 0)
Now 5 enabled devices.

Program received signal SIGSEGV, Segmentation fault.
on_motion (win=<optimized out>, ev=0x869ae0, user_data=0x751150) at callbacks.c:309
309	  if (ev->state != masterdata->state ||
Missing separate debuginfos, use: dnf debuginfo-install atk-2.16.0-2.fc23.x86_64 at-spi2-atk-2.16.0-2.fc23.x86_64 at-spi2-core-2.16.0-2.fc23.x86_64 bzip2-libs-1.0.6-16.fc23.x86_64 cairo-1.14.2-2.fc23.x86_64 cairo-gobject-1.14.2-2.fc23.x86_64 dbus-libs-1.9.16-2.fc23.x86_64 elfutils-libelf-0.163-1.fc23.x86_64 elfutils-libs-0.163-1.fc23.x86_64 expat-2.1.0-12.fc23.x86_64 fontconfig-2.11.94-2.fc23.x86_64 freetype-2.6.0-2.fc23.x86_64 gdk-pixbuf2-2.31.4-2.fc23.x86_64 gdk-pixbuf2-modules-2.31.4-2.fc23.x86_64 glib2-2.45.3-2.fc23.x86_64 graphite2-1.2.4-5.fc23.x86_64 gtk3-3.17.4-1.fc23.x86_64 gvfs-client-1.25.2-3.fc23.x86_64 harfbuzz-0.9.41-1.fc23.x86_64 libattr-2.4.47-12.fc23.x86_64 libbluray-0.8.0-3.fc23.x86_64 libcanberra-0.30-10.fc23.x86_64 libcanberra-gtk3-0.30-10.fc23.x86_64 libcap-2.24-8.fc23.x86_64 libdatrie-0.2.8-6.fc23.x86_64 libdrm-2.4.61-4.fc23.x86_64 libepoxy-1.2-4.fc23.x86_64 libffi-3.1-8.fc23.x86_64 libgcc-5.1.1-4.fc23.x86_64 libgcrypt-1.6.3-5.fc23.x86_64 libgpg-error-1.19-2.fc23.x86_64 libogg-1.3.2-4.fc23.x86_64 libpng-1.6.17-2.fc23.x86_64 libselinux-2.3-11.fc23.x86_64 libtdb-1.3.6-2.fc23.x86_64 libthai-0.1.21-2.fc23.x86_64 libtool-ltdl-2.4.6-5.fc23.x86_64 libvorbis-1.3.4-5.fc23.x86_64 libwayland-client-1.7.92-2.fc23.x86_64 libwayland-cursor-1.7.92-2.fc23.x86_64 libwayland-server-1.7.92-2.fc23.x86_64 libX11-1.6.3-2.fc23.x86_64 libXau-1.0.8-5.fc23.x86_64 libxcb-1.11-8.fc23.x86_64 libXcomposite-0.4.4-7.fc23.x86_64 libXcursor-1.1.14-4.fc23.x86_64 libXdamage-1.1.4-7.fc23.x86_64 libXext-1.3.3-3.fc23.x86_64 libXfixes-5.0.1-5.fc23.x86_64 libXi-1.7.4-3.fc23.x86_64 libXinerama-1.1.3-5.fc23.x86_64 libxkbcommon-0.5.0-2.fc23.x86_64 libxml2-2.9.2-5.fc23.x86_64 libXrandr-1.5.0-2.fc23.x86_64 libXrender-0.9.9-2.fc23.x86_64 libxshmfence-1.2-2.fc23.x86_64 libXxf86vm-1.1.4-2.fc23.x86_64 mesa-libEGL-10.7.0-0.devel.1.8787141.fc23.x86_64 mesa-libgbm-10.7.0-0.devel.1.8787141.fc23.x86_64 mesa-libGL-10.7.0-0.devel.1.8787141.fc23.x86_64 mesa-libglapi-10.7.0-0.devel.1.8787141.fc23.x86_64 mesa-libwayland-egl-10.7.0-0.devel.1.8787141.fc23.x86_64 nss-softokn-freebl-3.19.2-2.fc23.x86_64 pango-1.37.1-1.fc23.x86_64 pcre-8.37-1.fc23.1.x86_64 pixman-0.32.6-6.fc23.x86_64 systemd-libs-221-1.fc23.x86_64 xz-libs-5.2.1-2.fc23.x86_64 zlib-1.2.8-8.fc23.x86_64

|> xsetpointer -l
2: "Virtual core pointer"	[XPointer]
3: "Virtual core keyboard"	[XKeyboard]
4: "Virtual core XTEST pointer"	[XExtensionPointer]
5: "Virtual core XTEST keyboard"	[XExtensionKeyboard]
6: "Power Button"	[XExtensionKeyboard]
7: "Video Bus"	[XExtensionKeyboard]
8: "Sleep Button"	[XExtensionKeyboard]
10: "ELAN Touchscreen"	[XExtensionPointer]
11: "Integrated Camera"	[XExtensionKeyboard]
12: "AT Translated Set 2 keyboard"	[XExtensionKeyboard]
13: "SynPS/2 Synaptics TouchPad"	[XExtensionPointer]
14: "TPPS/2 IBM TrackPoint"	[XExtensionPointer]
15: "ThinkPad Extra Buttons"	[XExtensionKeyboard]
9: "Wacom Graphire2 4x5 stylus"	[XExtensionPointer]
16: "Wacom Graphire2 4x5 eraser"	[XExtensionPointer]
17: "Wacom Graphire2 4x5 cursor"	[XExtensionPointer]

**Comment by russel** [comment]
I just tried compiling and using this instead of the packaged version on Debian and it seems to work fine. So it is clearly a change in something on Fedora Rawhide.

**Comment by bk138** [comment]
still the case?

**Comment by bk138** [comment]
Closing now, pls reopen if issue persists.
