### ISSUE TITLE
Automatic smoothing of hand-drawn lines

### ISSUE THREAD

**Issue by pascal-niklaus** [bk138/gromit-mpx#194]
**Is your feature request related to a problem? Please describe.**

Hand-drawn lines often look shaky... 

**Describe the solution you'd like**

...applying some smoothing algorithm can clean-up such lines

**Possible solution**

Since I have been playing with the gromit source code, I have also implemented a smoothing option. 

Basically, when a line is completed, it first applies a point reduction using the Douglas-Peucker algorithm, and then interpolates among the remaining points with centripetal Catmull-Rom splines.

The general shape and start and end points are preserved, and the smoothing degree can be set.

Here is an example with relatively strong smoothing.

![gromit_smoothing](https://github.com/bk138/gromit-mpx/assets/9673983/5fbfabde-5b5e-4cc5-a4b2-b1fd8f8d800a)

Before spamming this repo with PRs, I wanted to discuss (1) whether such an option is useful, and, if yes, (2) how it is best integrated. For the moment, I just have an additional tool called SMOOTH, but there could be a "smooth=..." option for the PEN tool.

To provide a perspective on the extent of code addition, the entire smoothing logic is a bit less than 200 lines of code, in an additional file smooth.c.

**Comment by bk138** [comment]
@pascal-niklaus Neat idea! Sorry for the delay, I was busy with €€€-work. I guess a separate tool aka GromitPaintContext makes sense as the smoothing is not applicable to ERASER, RECOLOR OR LINE. Maybe call it SMOOTH_PEN ?

**Comment by bk138** [comment]
Implemented by 19a55699e23ff63106c12f34f30aa8f093a44c65
