### ISSUE TITLE
Inability to add LINE and RECT in .cfg file

### ISSUE THREAD

**Issue by AdityaS8804** [bk138/gromit-mpx#208]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

**Describe the bug**
The recent release of RECT and LINE features do not work in .cfg file. When I tried to add  to gromit-mpx.cfg:
...
"green Line"= LINE(color="green")
default="green Line"
...
It thows - Enter definition or tool 

**To Reproduce**
1. go to ~/.config
2. create gromit-mpx.cfg
3. Add these : 
"green Line"= LINE(color="green")
default="green Line"
 and save
5. Run the program
 
**Expected Behavior**
Straight line with green arrow to be drawn on screen

**Screenshots**
![Screenshot_2024-05-20_22-34-32](https://github.com/bk138/gromit-mpx/assets/121397817/aee4fa0b-aac4-4b17-a796-aeba72c7bacc)
![Screenshot_2024-05-20_22-33-55](https://github.com/bk138/gromit-mpx/assets/121397817/cb3202de-502a-4c6b-8005-f0346af9df6f)

**Environment (please complete the following information):**
 - Gromit-MPX version: 1.6.0
 - Flatpak or Distribution-package or Built-from-source: apt
 - OS and version: kali purple
 - Desktop Environment and version: xfce 
 - X11 or Wayland session: X11

**Comment by bk138** [comment]
You're missing semicola and quotes for the default tool, see https://github.com/bk138/gromit-mpx#configuration

This is what works for me:

```
"green Line" = LINE (color="green");
"default" = "green Line";
```

Manula config file editing will go away, see #110.

Please re-open if issue persists.

**Comment by AdityaS8804** [comment]
Hey, thanks for the response.
Even with the semicolon added, the issue persists for me, with the same error messages. Here is my complete gromit-mpx.cfg file:
```
# Tool and hot key configuration for Gromit-MPX.
#
# See https://github.com/bk138/gromit-mpx/blob/master/README.md#configuration
# for what you can configure here and how the syntax looks like.
#
# ❗ Once done editing, you have to manually restart Gromit-MPX to apply the
# made changes.
#
# Note that there is https://github.com/bk138/gromit-mpx/issues/110 which will
# eventually replace this with a proper UI.
# 

# 
# Tool definitions.
#
#
# Tool mappings to input devices. Not all tools are mapped in this config.
#
"green Line"= LINE (color="green");
"default"="green Line";
#
# Hot key / undo key.
# Uncomment to set Hot key and/or Undo key to a custom value. Note that you can only specify single keysyms, not >
#

# HOTKEY = "F9";
# UNDOKEY = "F8";
```

Please re-open the issue and look into the same. 
Much appreciated.

**Comment by bk138** [comment]
Your snippet works for me. Please make sure you're editing the right config file.
