### ISSUE TITLE
Can't Quit Program

### ISSUE THREAD

**Issue by Skribbles32** [bk138/gromit-mpx#209]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

**Describe the bug**
When I try to quit Gromit-MPX (Either through the shortcut or the menu) nothing happens. It just stays open.

**To Reproduce**
1. Launch Gromit-MPX
2. Either press CTRL-F9, or try to quit from the menu.

**Expected Behaviour**
I expected Gromit-MPX to close.

**Environment (please complete the following information):**
 - Gromit-MPX version: 1.6.0
 - Flatpak or Distribution-package or Built-from-source: Flatpak
 - OS and version: Ubuntu 20.04.6 LTS
 - Desktop Environment and version: GNOME 3.36.8
 - X11 or Wayland session: Wayland

**Comment by bk138** [comment]
OK this can be closed then?
