### ISSUE TITLE
Update or remove snap?

### ISSUE THREAD

**Issue by Req** [bk138/gromit-mpx#216]
I've been recommending this to quite a few people and sometimes they install the snap version, which apparently can have issues due to being outdated.

Maybe it would make sense to remove the snap or update it? I have no idea what the process is like; could anyone help out with that?

**Comment by bk138** [comment]
Hi @Req,
Thanks so much for recommending! Regarding the snap, however, I fear this is something that the Ubuntu people need to fix (or whoever provides this).

PS from https://snapcraft.io/gromit-mpx I see that https://snapcraft.io/publisher/niemeyer might be the person to reach out to. They might be @niemeyer but not 100% sure 😇
