### ISSUE TITLE
./configure issue: `PKG_PROG_PKG_CONFIG(0.20)'

### ISSUE THREAD

**Issue by AJNOURI** [bk138/gromit-mpx#24]
From github repo and after ***autoreconf --install***, got this error on ***./configure***:

> ./configure: line 3953: syntax error near unexpected token `0.20'
>
> ./configure: line 3953: `PKG_PROG_PKG_CONFIG(0.20)'

**Comment by bk138** [comment]
apt-get install pkg-config
