### ISSUE TITLE
Wish List: text, opacity++, exporting, line style, usability

### ISSUE THREAD

**Issue by anderflash** [bk138/gromit-mpx#25]
- Text:
  - font
  - color
  - size
- Opacity:
  - different opacity values for specific pens
  - shortcut for opacity++ and opacity-- for pens without fixed opacity values
- Exporting
  - just the drawings (transparent png, svg, pdf,...)
  - drawing+screen (png, jpg, pdf...)
- Line style: solid, dash, dots...
- Usability
  - An informative small panel (like conky): current pen color, size, opacity, line style.
- Shapes: rectangle, circle, star, triangle...
- Smoothness: gimp has some pencil styles to get better curves (I tend to have shaky curves without it).
- Color Palette: a list of squares offering visual color switching.

**Comment by bk138** [comment]
Hi @anderflash, did you have a look at https://github.com/gfreeau/ardesia?

**Comment by bk138** [comment]
General update: issues with Gromit-MPX can now be funded at https://issuehunt.io/r/bk138/gromit-mpx

**Comment by bk138** [comment]
As this issue is requesting a lot of things at once, I'll close it. Let's track individual features in
* #104 for text
* #87 for opacity
* #67 for straight lines
* and #57 for informative icon
