### ISSUE TITLE
Proper interaction with Wayland

### ISSUE THREAD

**Issue by tobias47n9e** [bk138/gromit-mpx#27]
When launching Gromit on Fedora 24 in the Gnome Wayland session I get this error:

```
Supported backends: x11 wayland 
Using backend: wayland

(gromit-mpx:24312): GLib-GObject-WARNING
     **: g_object_get_valist: object class
    'GdkWaylandDevice' has no property named 'device-id'
Segmentation fault (core dumped)
```

Using the x11 session on the same machine works perfectly.

And thank you for making such a useful tool!

**Comment by bk138** [comment]
IIRC, wayland support is still preliminary. If you want to finish that, go ahead! :-)

**Comment by tobias47n9e** [comment]
I would like to, but I wouldn't even know where to start. I never tried migrating anything to Wayland before.

**Comment by bk138** [comment]
First stab would be to remove device-id access, at GdkDevice does not have this anymore https://developer.gnome.org/gdk3/stable/GdkDevice.html

**Comment by bk138** [comment]
For a), there is https://developer.gnome.org/gdk3/stable/GdkDevice.html#gdk-device-grab and friends for the grabs, whicht at the time of writing were broken and required me to use the XINput functions...

**Comment by tobias47n9e** [comment]
I had a chat with some of the Gnome developers on IRC. Because Wayland restricts programs from drawing over other programs for security reasons, the only way to have a program like Gromit under Wayland would be to (quote):

> either it is in the compositor or it needs a protocol

At the moment that seems quite complicated. I might need to revisit this issue once I have a better understanding of all the parts involved. Thank you too, for explaining some of the first steps!

**Comment by russel** [comment]
I have no technical input here, just to say that I use Gromit-MPX for all my presentations at conferences and during workshops. It has become a bit of a USP, and people are always asking what software I am using. Of course I tell them, hopefully this means more users – though many of them are Windows and macOS people…

Fedora is again trying to push Wayland as the default, and ditch X – I dual boot Debian Sid and Fedora Rawhide, Sid is still very much Xorg and no Wayland, Rawhide is Wayland by default but with Xorg as an option. I understand though that Xwayland is actually a hybrid; Wayland but with X-y bits. If Gromit-MPX cannot be made to work on Wayland, then I shall remain an Xorg holdout. I appreciate that Wayland is better than Xorg conceptually, but this is about what users want to do with their computers!

I had stopped recompiling Gromit-MPX each day as I needed a stable working version guaranteed for conferences and workshops. I will though set up to do daily builds and check on Sid and Rawhide if that will help.

**Comment by bk138** [comment]
Thank you @russel ! What's needed most is some more dev personnel as I am seriously lacking time. PRs are always welcome ;-)

**Comment by bk138** [comment]
@russel Ah and have you tried Wayland support of ardesia or spotlighter?

**Comment by bk138** [comment]
@tobias47n9e I was curious and just tried it out in a wayland session and gromit-mpx worked surpisingly well under XWayland. When passing in GDK_BACKEND=wayland I got the same error as you. Did you try

    GDK_BACKEND=x11 gromit-mpx -d

?

**Comment by bk138** [comment]
@tobias47n9e can you pls try 5e9aeb37d503c06d59808a97928af5b7d5320923 ?

**Comment by tobias47n9e** [comment]
After applying the patch I could launch the program using `GDK_BACKEND=x11 gromit-mpx -d`. Pressing F9 launches the draw cursor, but only after clicking on another program, clicking on the desktop is not enough). Drawing itself does not seem to work. Pressing F9 again correctly ends the drawing mode. An interesting thing is that the terminal used to launch Gromit is not selectable by mouse anymore, but just by keyboard.

**Comment by bk138** [comment]
To clarify: https://github.com/bk138/gromit-mpx/commit/5e9aeb37d503c06d59808a97928af5b7d5320923 should make the manual GDK_BACKEND setting obsolete. Can you test this?

Did you launch gromit-mpx from the terminal? It seems doing make install and using the GNOME launcher makes a difference...

**Comment by tobias47n9e** [comment]
Not sure why GDK_BACKEND is not chosen automatically, but it doesn't work. After a restart oddly enough I could get drawing to work. After exiting and launching again, drawing does not work anymore.

I am launching from the terminal. Using the icon segfaults like using only `gromit-mpx` to launch the program. Probably not enough information to debug the issue.

**Comment by bk138** [comment]
Few points here:
* restart of gromit or your Wayland session?
* you probably should *not* launch from the terminal but the launcher after sudo make install. pls also make sure you haven't installed the rpm/deb package as there might be concflicts.
* can you give some info about your environment? OS, desktop, etc with versions. I could setup a virtual machine and try myself...

**Comment by tobias47n9e** [comment]
* A system restart
* I didn't install an rpm package of gromit
* I am using Fedora 24 with a standard installation and Gnome desktop.

I am thinking of updating to Fedora 25 alpha soon, to try it with the newer Wayland packages.

**Comment by russel** [comment]
Sorry I haven't been able to chip in this for the last day or so. I should be able to try things out on Fedora Rawhide (F26 currently) over the weekend.

**Comment by bk138** [comment]
a3bd7ab8028d4544d7396e9bcf69abdf2862356a should fix that particular issue here, but not the Wayland functionality as a whole...

**Comment by bk138** [comment]
General update: issues with Gromit-MPX can now be funded at https://issuehunt.io/r/bk138/gromit-mpx

**Comment by bk138** [comment]
Getting back to this, here a some things that need fixing

* [ ] the hotkey has to be defined in the compositor, for gnome-shell this could be sth like https://askubuntu.com/a/597414/344291
* [ ] the IPC via selections does not work as expected under Wayland

**Comment by bk138** [comment]
Closing as as basic functionality works, #103 and #106 keep track of remaining Wayland-related issues.

**Comment by RichardFevrier** [comment]
Sorry to dig this issue but is it using Xwayland or native Wayland @bk138 ?

**Comment by bk138** [comment]
@RichardFevrier no problem ;-) yes, XWayland.
