### ISSUE TITLE
Switch from Autotools to SCons, Meson, or CMake?

### ISSUE THREAD

**Issue by russel** [bk138/gromit-mpx#28]
I have been working on bits of SCons for a while now and it is way better than Autotools for C, C++, Fortran, D, and LaTeX builds. However the CLion IDE has gone the CMake route. CMake is second rate (in my view) to SCons, but to use CLion is to use CMake. GStreamer (on which I am scheduled to do some work fairly soon) has been an Autotools project. It has recently though added Meson build. It seems as though the GTK-based community may be shifting from Autotools to Meson. Meson is CMake is architecture but has a Python-style DSL and Ninja back-end rather than CMake's weird DSL and Make.

I have only had a little bit of experience with Meson to date, but it certainly looks like a very good system.  Is there a chance of admitting a change of build infrastructure. As you can tell I really do not like Autotools!

**Comment by bk138** [comment]
I prefer CMake, so if you want to exchange Autotools for CMake, go ahead!

**Comment by barak** [comment]
I have a new bicycle shed but I'm not sure what colour to paint it, perhaps you can help me decide?

**Comment by russel** [comment]
The bikeshed will be orange, no other colour (or is that color) is acceptable.

**Comment by barak** [comment]
First we need to form a subcommittee to decide which way to spell it: color or colour.

**Comment by russel** [comment]
Or maybe we just create a CMake build and get on with stuff… It'll have to be in a couple of weeks time, but I will certainly give it a go – it will then allow me to use CLion for working on this project.

**Comment by barak** [comment]
> I really do not like Autotools

Nobody likes autotools! But they do work.

Is there something missing from the autotools scripts right now?

**Comment by russel** [comment]
I will be looking to create a CMake build for Gromit-MPX shortly, sorry it has taken me longer than expected to get to this. Long story.

**Comment by russel** [comment]
Pull request #33 addresses the CMake issue. This is needed to be able to use CLion as an IDE. At least currently. One hopes they will also support Meson in the future.

**Comment by bk138** [comment]
Closing as https://github.com/bk138/gromit-mpx/pull/33 got merged.
