### ISSUE TITLE
Visually inconsistent behaviour when drawing with 2 pointing devices attached to the same keyboard, i.e. trigger key

### ISSUE THREAD

**Issue by bk138** [bk138/gromit-mpx#29]

**Comment by bk138** [comment]
![bildschirmfoto von 2016-10-08 14 16 14](https://cloud.githubusercontent.com/assets/80450/19213061/e3706c04-8d61-11e6-8fc4-e8d278d0a15b.png)

**Comment by bk138** [comment]
Ha, this stems from two pointing devices on my Thinkpad being connected to the same set of buttons. Mhh, and now?

**Comment by russel** [comment]
I can report that on a Lenovo X1, with Wacom Tablet, Logitech USB mouse, ELAN Touchscreen, TPPS/2 IBM Trackpoint and SynPS/2 Synaptics Touchpad then when using the mouse, touchpad or touch screen I get a line from the previous end point to the new start point and then a line from the new end point to the new start point. Sadly this makes the touchpad and touchscreen unusable as input devices. The same problem does not happen using the trackpoint or a Wacom tablet. Removing the mouse and the tablet makes no difference, so it must be the built in combination that is problematic. I think this is just confirming the problem.

**Comment by vonpupp** [comment]
I confirm this issue also on a Lenovo X230 also. I get the following after I start the program:
```
Could not open /home/av/.config/gromit-mpx.cfg: No such file or directory
Could not open /etc/gromit-mpx/gromit-mpx.cfg: No such file or directory
Supported backends: x11 wayland 
Using backend: x11
Enabled Device 0: "Virtual core pointer", (Type: 0)
Enabled Device 1: "TPPS/2 IBM TrackPoint", (Type: 7)
Enabled Device 2: "SynPS/2 Synaptics TouchPad", (Type: 6)
Enabled Device 3: "Virtual core XTEST pointer", (Type: 0)
Now 4 enabled devices.

(gromit-mpx:9009): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

I am using Awesome WM without composite on Arch Linux. Any idea?

Thanks.

**Comment by bk138** [comment]
See above.
> two pointing devices on my Thinkpad being connected to the same set of buttons.

**Comment by vonpupp** [comment]
Sorry but I just installed gromit-mpx and I am not familiarized with it yet.

Could you please elaborate on how to blacklist the other devices on gromit-mpx? I don't have external devices connected to the notebook, I am not sure why it recognizes 4 devices.

Thanks.

**Comment by bk138** [comment]
You see the devices built into your machine. Maybe setting master/slaves via https://linux.die.net/man/1/xinput helps.

**Comment by vonpupp** [comment]
Hi, thank you for your help.

Here is the output of xinput:
```
> $ xinput                                                                                                                                                               
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=11	[slave  pointer  (2)]
⎜   ↳ TPPS/2 IBM TrackPoint                   	id=12	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=9	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=10	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=13	[slave  keyboard (3)]
```

When I disable id=11 only, I cannot move the pointer. When I disable id=12 only, I cannot click. Any other idea?

**Comment by bk138** [comment]
Works before 58bdef4d49ab4269fedda55e825ce8ad8a62076c

**Comment by dmusican** [comment]
I'm experiencing a version of this problem. I see that this issue is closed, but it's unclear to me what the resolution was. Is it believed that the problem was fixed, and if so, should I be posting this as a new bug?
