### ISSUE TITLE
git tag for version 1.2

### ISSUE THREAD

**Issue by wikimatze** [bk138/gromit-mpx#31]
Hi there, I installed everything from master and was wondering why there isn't a 1.2 tag in the repository.

Thanks for the great tool.

Cheers from Berlin,

Matthias

**Comment by bk138** [comment]
'cause 'it's not done yet' - especially wayland (non)support is missing. care to help?

**Comment by wikimatze** [comment]
Sure let me know who to help. By the way is there a way to use a gitter(grid so that I can draw straight forward line.

**Comment by russel** [comment]
@bk138 I can certainly help testing this. I believe Debian Sid has reinstated a XWayland login, and Fedora Rawhide has it as the default.

**Comment by bk138** [comment]
Closed by a835decff6d0186bd96075bca8ed31144f2ff9e2 :-)

**Comment by wikimatze** [comment]
Hurray!
