### ISSUE TITLE
Installation on Ubuntu 16.10

### ISSUE THREAD

**Issue by orschiro** [bk138/gromit-mpx#32]
Dear @bk138,

Thanks for this excellent and promising program!

I installed it on Ubuntu 16.10 but how do I use it?

Running `gromit-mpx` from the command-line doesn't bring up any window, tray icon or error message.

Thank you!

-Robert

```
orschiro@x230:~$ sudo apt install gromit-mpx
[sudo] password for orschiro: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  gromit-mpx
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 28,3 kB of archives.
After this operation, 141 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu yakkety/universe amd64 gromit-mpx amd64 1.1+git.1.fb3c7f8-1 [28,3 kB]
Fetched 28,3 kB in 0s (65,3 kB/s)     
Selecting previously unselected package gromit-mpx.
(Reading database ... 406563 files and directories currently installed.)
Preparing to unpack .../gromit-mpx_1.1+git.1.fb3c7f8-1_amd64.deb ...
Unpacking gromit-mpx (1.1+git.1.fb3c7f8-1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3+16.10.20160929-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Setting up gromit-mpx (1.1+git.1.fb3c7f8-1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu4) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
```

**Comment by bk138** [comment]
Thank you!
Does the menu entry shows up in GNOME shell? IIRC, tray icons are not shown anymore in newer versions of GNOME 3. I recently tested with Fedora and they had a tray in the lower left corner, YMMV...

**Comment by orschiro** [comment]
Hi Christian,

I don't have Gnome Shell but Ubuntu 16.10 Unity. All other programs
properly show tray icons.

**Comment by bk138** [comment]
Okay, for the tray icon: those are not supported on Unity, see http://askubuntu.com/a/19860/344291. Someone needs to implement an appindicator-style icon or use https://wiki.gnome.org/HowDoI/GNotification since GtkStatusIcon is deprecated anyway...

**Comment by bk138** [comment]
BTW, you still can use gromit-mpx perfectly fine without the tray icon! Just memorise the keyboard shortcuts!

**Comment by russel** [comment]
I use Gromit-MPX with Debian Sid and GNOME Shell. I have Fedora Rawhide, but I am not using just at the moment. I certainly do have a tray on GNOME Shell, it is bottom left but only appears as an arrow to get the drawer to appear. On my workstation, I get 3 icon spaces used but none have an image and none do anything. On my laptop, I also get three icon spaces, one has an icon, looks like a green M, and clicking it gives a menu. I didn't know this existed till today. I am not using the Debian packages but a compilation of the Git repository source, I'm not exactly sure which version. I have only ever used the touch screen or a Wacom tablet, though I know things work with the mouse or touchpad directly.  My biggest problems are remembering which colour/feature is associated with each keystroke and mouse movement combination.

**Comment by orschiro** [comment]
Hi all, 

Do I need to have a tablet to use gromit-mpx?

I ran gromit-mpx on my Thinkpad X230 but none of the keyboard shortcuts work. 

```
orschiro@x230:~$ gromit-mpx 
Supported backends: x11 wayland 
Using backend: x11
Enabled Device 0: "Virtual core pointer", (Type: 0)
Enabled Device 1: "TPPS/2 IBM TrackPoint", (Type: 0)
Enabled Device 2: "SynPS/2 Synaptics TouchPad", (Type: 6)
Enabled Device 3: "Virtual core XTEST pointer", (Type: 0)
Now 4 enabled devices.
^[[20~
```

Clicking with my mouse I cannot draw any annotations.

**Comment by bk138** [comment]
The default shortcut is F9, IIRC Debian changed this to F12. Try running gromit-mpx with the -d switch.

**Comment by orschiro** [comment]
Dear all, 

I hope the following GIF animation better illustrates my problem. 

I just don't understand how to annotate (draw) on my screen on my Thinkpad X230 which is not a tablet but a normal laptop.

![gromit](https://cloud.githubusercontent.com/assets/170947/20239976/47e911e2-a90d-11e6-90d9-f36c089eb80e.gif)

**Comment by bk138** [comment]
First of all: you can use gromit-mpx on a laptop perfectly fine, no need for a tablet.
Then: I've added Unity appindicator support to the master branch. Pls check that out.
Finally: I've tried master on a fresh Ubuntu 16.10 install and it works just fine.

**Comment by orschiro** [comment]
Look at this, it is fantastic! :-)

Thank you so much!

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/20240806/0a49c858-a922-11e6-874a-120f74b2fdd6.png)

**Comment by bk138** [comment]
Cool! Nice I could help.
