### ISSUE TITLE
1.1 -> 1.2 update: build fails on undocumented missing dependency

### ISSUE THREAD

**Issue by Vaelatern** [bk138/gromit-mpx#35]
```
checking for APPINDICATOR... no
configure: error: Package requirements (appindicator3-0.1 >= 0.4.92) were not met:

No package 'appindicator3-0.1' found
```

Technically this is a documented missing dependency, since the build demands it. Is this an artifact of building from the git tarballs?

**Comment by bk138** [comment]
Well, it's a dependency. Where were those documented before?

**Comment by Vaelatern** [comment]
At build time, in the README.

**Comment by bk138** [comment]
To be clear here: I do not intend to document maybe-changing build deps in any other place than the build system itself. Feel free to open a PR removing the respective bits from the README.

**Comment by tobias47n9e** [comment]
@Vaelatern Did you figure out which package that is? I am not sure either which one it is on Fedora. Is it maybe a Ubuntu-only package?

**Comment by russel** [comment]
appindicator is definitely in Debian (libappindicator3-dev), or I wouldn't be able to build Gromit-MPX. Whether Debian gets it from Ubuntu or Ubuntu gets it from Debian I am not sure. It is also in Fedora (libappindicator-gtk3-devel), though I haven't tried building it yet, I am just about to.

**Comment by russel** [comment]
All compiles fine on Fedora but doesn't work on the Rawhide default of XWayland. Works fine(-ish, I see a bug) on Xorg.

**Comment by bk138** [comment]
@russel bug?

**Comment by russel** [comment]
@bk138 I believe so: the behaviour on Fedora/Xorg appears different (and unreasonable) compared to Debian/Xorg. In particular end the end of a simple drawing action a line from beginning to end of the newly drawn line is added in on Fedora but not on Debian. I can't follow up on this till the end of the week – I have to go somewhere for a couple of days and use Gromit-MPX a lot. On Debian. :-)

**Comment by bk138** [comment]
@russel might be https://github.com/bk138/gromit-mpx/issues/29 ?

**Comment by russel** [comment]
@bk138 Possibly, but I won't be able to investigate this properly till Friday or more likely next week. Sorry.
