### ISSUE TITLE
Is the manpage missing a section on FILES?

### ISSUE THREAD

**Issue by russel** [bk138/gromit-mpx#37]
I was looking in the man page for the location of the user configuration files, but couldn't see a FILES section. Is it missing or did I just miss it?

Also the man page doesn't explain how to configure using files.

**Comment by bk138** [comment]
yeah, that could be added.

**Comment by bk138** [comment]
Always happy about a PR @russel  ;-)

**Comment by russel** [comment]
Wilco, but I am too busy using Gromit-MPX in a workshop just now. :-)

**Comment by bk138** [comment]
Can this be closed @russel ?

**Comment by russel** [comment]
It would appear that someone stepped into the hole left by me not doing what I said I would do. Thanks to @barak. (The last 8 weeks have not been good in our household. Long (boring) story.)
