### ISSUE TITLE
compilation error for the recent release

### ISSUE THREAD

**Issue by DrWaleedAYousef** [bk138/gromit-mpx#38]
I just installed Archlinux on a new laptop; therefore I had to re-install gromit using the new cmake configuration (as opposed to the old one using autconf.) it gives me this:
-- The C compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gtk+-3.0 >= 2.99.3'
--   Found gtk+-3.0 , version 3.22.4
-- Checking for module 'appindicator3-0.1 >= 0.4.92'
--   
CMake Error at /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:424 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
  CMakeLists.txt:14 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeOutput.log".

**Comment by russel** [comment]
Hummm… at first sight this would seem to be a CMake installation problem not a Gromit-MPX build problem. I would suggest reinstalling the cmake package – looking at the Arch package listings they package things very differently to Debian and Fedora, so I have no suggestions to offer other than "try reinstalling cmake".

**Comment by DrWaleedAYousef** [comment]
I re-installed; did not work: this is the log file. (also, what is the difference between this recent version and the old one that we used to install using autoconf.):

The system is: Linux - 4.8.11-1-ARCH - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc 
Build flags: 
Id flags: 

The output was:
0


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is GNU, found in "/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/3.6.3/CompilerIdC/a.out"

Determining if the C compiler works passed with the following output:
Change Dir: /home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_4fa5e/fast"
/usr/bin/make -f CMakeFiles/cmTC_4fa5e.dir/build.make CMakeFiles/cmTC_4fa5e.dir/build
make[1]: Entering directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_4fa5e.dir/testCCompiler.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_4fa5e.dir/testCCompiler.c.o   -c /home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_4fa5e
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4fa5e.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_4fa5e.dir/testCCompiler.c.o  -o cmTC_4fa5e -rdynamic 
make[1]: Leaving directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp'


Detecting C compiler ABI info compiled with the following output:
Change Dir: /home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_b83a3/fast"
/usr/bin/make -f CMakeFiles/cmTC_b83a3.dir/build.make CMakeFiles/cmTC_b83a3.dir/build
make[1]: Entering directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_b83a3.dir/CMakeCCompilerABI.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_b83a3.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.6/Modules/CMakeCCompilerABI.c
Linking C executable cmTC_b83a3
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b83a3.dir/link.txt --verbose=1
/usr/bin/cc      -v CMakeFiles/cmTC_b83a3.dir/CMakeCCompilerABI.c.o  -o cmTC_b83a3 -rdynamic  
Using built-in specs.
COLLECT_GCC=/usr/bin/cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.2.1 20160830 (GCC) 
COMPILER_PATH=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/:/lib/../lib/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_b83a3' '-rdynamic' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/collect2 -plugin /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper -plugin-opt=-fresolution=/tmp/ccKxNgvC.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_b83a3 /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/crt1.o /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/crti.o /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/crtbegin.o -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1 -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../.. CMakeFiles/cmTC_b83a3.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/crtend.o /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/crtn.o
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_b83a3' '-rdynamic' '-mtune=generic' '-march=x86-64'
make[1]: Leaving directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp'


Parsed C implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command:"/usr/bin/make" "cmTC_b83a3/fast"]
  ignore line: [/usr/bin/make -f CMakeFiles/cmTC_b83a3.dir/build.make CMakeFiles/cmTC_b83a3.dir/build]
  ignore line: [make[1]: Entering directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp']
  ignore line: [Building C object CMakeFiles/cmTC_b83a3.dir/CMakeCCompilerABI.c.o]
  ignore line: [/usr/bin/cc     -o CMakeFiles/cmTC_b83a3.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.6/Modules/CMakeCCompilerABI.c]
  ignore line: [Linking C executable cmTC_b83a3]
  ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b83a3.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/cc      -v CMakeFiles/cmTC_b83a3.dir/CMakeCCompilerABI.c.o  -o cmTC_b83a3 -rdynamic  ]
  ignore line: [Using built-in specs.]
  ignore line: [COLLECT_GCC=/usr/bin/cc]
  ignore line: [COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper]
  ignore line: [Target: x86_64-pc-linux-gnu]
  ignore line: [Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release]
  ignore line: [Thread model: posix]
  ignore line: [gcc version 6.2.1 20160830 (GCC) ]
  ignore line: [COMPILER_PATH=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/]
  ignore line: [LIBRARY_PATH=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/:/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/:/lib/../lib/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../:/lib/:/usr/lib/]
  ignore line: [COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_b83a3' '-rdynamic' '-mtune=generic' '-march=x86-64']
  link line: [ /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/collect2 -plugin /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper -plugin-opt=-fresolution=/tmp/ccKxNgvC.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_b83a3 /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/crt1.o /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/crti.o /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/crtbegin.o -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1 -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../.. CMakeFiles/cmTC_b83a3.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/crtend.o /usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/crtn.o]
    arg [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/collect2] ==> ignore
    arg [-plugin] ==> ignore
    arg [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/liblto_plugin.so] ==> ignore
    arg [-plugin-opt=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper] ==> ignore
    arg [-plugin-opt=-fresolution=/tmp/ccKxNgvC.res] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [-plugin-opt=-pass-through=-lc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [--build-id] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [--hash-style=gnu] ==> ignore
    arg [-m] ==> ignore
    arg [elf_x86_64] ==> ignore
    arg [-export-dynamic] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
    arg [-o] ==> ignore
    arg [cmTC_b83a3] ==> ignore
    arg [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/crt1.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/crti.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/crtbegin.o] ==> ignore
    arg [-L/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1] ==> dir [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1]
    arg [-L/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib] ==> dir [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib]
    arg [-L/lib/../lib] ==> dir [/lib/../lib]
    arg [-L/usr/lib/../lib] ==> dir [/usr/lib/../lib]
    arg [-L/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../..] ==> dir [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../..]
    arg [CMakeFiles/cmTC_b83a3.dir/CMakeCCompilerABI.c.o] ==> ignore
    arg [-lgcc] ==> lib [gcc]
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--no-as-needed] ==> ignore
    arg [-lc] ==> lib [c]
    arg [-lgcc] ==> lib [gcc]
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--no-as-needed] ==> ignore
    arg [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/crtend.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/crtn.o] ==> ignore
  remove lib [gcc]
  remove lib [gcc_s]
  remove lib [gcc]
  remove lib [gcc_s]
  collapse library dir [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1] ==> [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1]
  collapse library dir [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib] ==> [/usr/lib]
  collapse library dir [/lib/../lib] ==> [/lib]
  collapse library dir [/usr/lib/../lib] ==> [/usr/lib]
  collapse library dir [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../..] ==> [/usr/lib]
  implicit libs: [c]
  implicit dirs: [/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1;/usr/lib;/lib]
  implicit fwks: []




Detecting C [-std=c11] compiler features compiled with the following output:
Change Dir: /home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_5c6f2/fast"
/usr/bin/make -f CMakeFiles/cmTC_5c6f2.dir/build.make CMakeFiles/cmTC_5c6f2.dir/build
make[1]: Entering directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_5c6f2.dir/feature_tests.c.o
/usr/bin/cc    -std=c11 -o CMakeFiles/cmTC_5c6f2.dir/feature_tests.c.o   -c /home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_5c6f2
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5c6f2.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_5c6f2.dir/feature_tests.c.o  -o cmTC_5c6f2 -rdynamic 
make[1]: Leaving directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:1c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c99] compiler features compiled with the following output:
Change Dir: /home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6a715/fast"
/usr/bin/make -f CMakeFiles/cmTC_6a715.dir/build.make CMakeFiles/cmTC_6a715.dir/build
make[1]: Entering directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6a715.dir/feature_tests.c.o
/usr/bin/cc    -std=c99 -o CMakeFiles/cmTC_6a715.dir/feature_tests.c.o   -c /home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_6a715
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6a715.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_6a715.dir/feature_tests.c.o  -o cmTC_6a715 -rdynamic 
make[1]: Leaving directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c90] compiler features compiled with the following output:
Change Dir: /home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_26f0e/fast"
/usr/bin/make -f CMakeFiles/cmTC_26f0e.dir/build.make CMakeFiles/cmTC_26f0e.dir/build
make[1]: Entering directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_26f0e.dir/feature_tests.c.o
/usr/bin/cc    -std=c90 -o CMakeFiles/cmTC_26f0e.dir/feature_tests.c.o   -c /home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_26f0e
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_26f0e.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_26f0e.dir/feature_tests.c.o  -o cmTC_26f0e -rdynamic 
make[1]: Leaving directory '/home/wyousef/MyDocuments/MyScripts/InstallationTipsArch/gromit-mpx/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:0c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:0c_variadic_macros

**Comment by bk138** [comment]
@DrWaleedAYousef appindicator3-dev package is installed, yeah?

**Comment by DrWaleedAYousef** [comment]
where is that? I cannot find it in either pacman or yaourt!!

**Comment by russel** [comment]
@bk138 I was clearly asleep earlier, the problem is obvious if I had only actually looked properly. :-( Though it has to be said, the CMake error report leaves a lot to be desired.

@DrWaleedAYousef  I am guessing this is the package that is missing:  https://www.archlinux.org/packages/community/x86_64/libappindicator-gtk3/

**Comment by DrWaleedAYousef** [comment]
Thanks so much; working great. Just more two questions:

1- It seems that I ONLY need the generated executable gromit-mpx not the whole directory; so that I safely can do:
cp gromit-mpx /usr/local/bin/

2- How can I increase the number of undoes with F10.

Thanks so much for your great package that I use in all my online courses.

**Comment by russel** [comment]
@DrWaleedAYousef Regarding 1, The default install location is /usr/local, so with the default CMake build you should just be able to do make install and everything goes into the right place.

**Comment by DrWaleedAYousef** [comment]
I did (as you said on the page): 
cmake ..
make

nothing is created on /usr/local or /usr/local/bin.

Anyway, is the executable gromit-mpx all what is needed (without extra files in the build directory)?

**Comment by russel** [comment]
@DrWaleedAYousef I suggest:

cmake ..
make
make install

**Comment by DrWaleedAYousef** [comment]
ok, "make install" just copies ONLY gromit-mpx to /usr/local/bin/gromit-mpx/gromit-mpx

So, same effect as self-copy the executable file to wherever without any other additional files.

Thanks so much.

**Comment by DrWaleedAYousef** [comment]
Sorry; just a correction: it copies to the location /usr/local/bin/ directly. So, same effect. 

Thanks again.

**Comment by russel** [comment]
It should install much more than just the executable. I install to $HOME/Built rather than /usr/local, but:
```
|> make install
[100%] Built target gromit-mpx
Install the project...
-- Install configuration: "Release"
-- Installing: /home/users/russel/Built/bin/gromit-mpx
-- Installing: /home/users/russel/Built/share/applications/gromit-mpx.desktop
-- Installing: /home/users/russel/Built/etc/gromit-mpx/gromit-mpx.cfg
-- Installing: /home/users/russel/Built/share/doc/gromit-mpx/README.md
-- Installing: /home/users/russel/Built/share/doc/gromit-mpx/AUTHORS
-- Installing: /home/users/russel/Built/share/doc/gromit-mpx/ChangeLog
-- Installing: /home/users/russel/Built/share/doc/gromit-mpx/NEWS
-- Installing: /home/users/russel/Built/share/man/man1/gromit-mpx.1
-- Installing: /home/users/russel/Built/share/pixmaps/gromit-mpx.png
-- Installing: /home/users/russel/Built/share/pixmaps/gromit-mpx.xpm
-- Installing: /home/users/russel/Built/share/icons/hicolor/scalable/apps/gromit-mpx.svg
```

**Comment by DrWaleedAYousef** [comment]
yes; exactly. I just was looking at the directory /usr/local/bin. I checked the shell, it reports exactly as what you said. Thanks again.

**Comment by bk138** [comment]
ok wonderful, all fine then.
