### ISSUE TITLE
Hot Key in Config File

### ISSUE THREAD

**Issue by barak** [bk138/gromit-mpx#40]
For symmetry, it would be nice if the hot key could be defined in `gromit-mpx.cfg`

**Comment by bk138** [comment]
I agree ;-)

**Comment by micahscopes** [comment]
This would be very nice!

**Comment by bk138** [comment]
Pull request welcome ;-)

**Comment by micahscopes** [comment]
I just might!  Yesterday I made this nice config with lots of different
colored pens and stuff... I was thinking about sharing that as a "how to
example" for a screen with a built in wacom digitizer. The current
documentation took me a few reads to figure it out. So I'm more likely to
pull request something like that...

**Comment by bk138** [comment]
General update: issues with Gromit-MPX can now be funded at https://issuehunt.io/r/bk138/gromit-mpx
