### ISSUE TITLE
Escape key to exit painting

### ISSUE THREAD

**Issue by ChameleonScales** [bk138/gromit-mpx#42]
Hi,
I just installed Gromit-mpx and wanted to try painting right away but didn't know how to escape it. I was close to restarting my computer but fortunately logging out with Ctrl+Alt+Del and logging back in did the trick. Then I found about F9.
But Escape is the best button ever. It should always be there when you don't know how to get out of a situation.

**Comment by bk138** [comment]
You're right about Escape being the ultimate panic button, but that would require Gromit-MPX to grab that key just like it does with F9, which would make it unavailable to _any_ other program. We'll go for a  tell-the-user-beforehand solution with #56 .

**Comment by ChameleonScales** [comment]
I see.
I didn't know any key was available for other apps while you're painting. Most seem not to be but escape is indeed. Still I think it would be better to put its priority to GromitMPX.
