### ISSUE TITLE
Using this as a tool/library for drawing to the screen

### ISSUE THREAD

**Issue by tobimensch** [bk138/gromit-mpx#44]
Hello,

I'm interested in using a tool like this for writing text (and possibly rectangles and other shapes) on the screen as overlay.

Is there currently any way for sing gromit-mpx in this way?

I.e. I want to call gromit-mpx from a bash script and tell it to draw a black rectangle with such and such
text at such and such position. And to delete that overlay again after a certain period of time or when it is called again to undo it.

**Comment by bk138** [comment]
no, not yet.

**Comment by bk138** [comment]
but you might have a look at https://github.com/gfreeau/ardesia :-)
