### ISSUE TITLE
Toggle Painting option not working on raspbian

### ISSUE THREAD

**Issue by Jayce08** [bk138/gromit-mpx#45]
I am using Gromit-mpx on the latest version of Raspbian. All features are working fine except the toggle painting in the task bar icon. When you click it, nothing happens, the crosser doesn't show at all. Any reason it doesn't work or any chance it could get fix?

Also when you use an on screen keyboard, the "pause / break" key doesn't trigger the toggle painting but it works when you use an actual keyboard.

Thanks in advance, I hope I can get a response. :)

**Comment by bk138** [comment]
Of course you get a response ;-)

Can you try running gromit-mpx from a terminal with "-d" debug cmdline switch and post the output?

Also, version of raspbian, X11 etc would be nice!

**Comment by Jayce08** [comment]
This is what I got from gromit-mpx -d

pi@raspberrypi:~ $ gromit-mpx -d
Tool name: "Eraser|@0           ": Eraser,  width:  75, arrowsize: 0.00, color: #FF0000
Tool name: "default|@1          ": Pen,     width:   5, arrowsize: 0.00, color: #0000FF
Tool name: "default|@2          ": Pen,     width:   5, arrowsize: 0.00, color: #FFFF00
Tool name: "red Pen|@0          ": Pen,     width:   5, arrowsize: 0.00, color: #FF0000
Tool name: "default|B0          ": Pen,     width:   6, arrowsize: 1.00, color: #008000
Tool name: "default|@0          ": Pen,     width:   5, arrowsize: 0.00, color: #FF0000
Tool name: "green Marker|@0     ": Pen,     width:   6, arrowsize: 1.00, color: #008000
Tool name: "default|D0          ": Eraser,  width:  75, arrowsize: 0.00, color: #FF0000
Tool name: "yellow Pen|@0       ": Pen,     width:   5, arrowsize: 0.00, color: #FFFF00
Tool name: "blue Pen|@0         ": Pen,     width:   5, arrowsize: 0.00, color: #0000FF
Supported backends: x11 wayland 
Using backend: x11
DEBUG: Ungrabbed all Devices.
DEBUG: Grabbing hotkeys from keyboard '3' .
Enabled Device 0: "Virtual core pointer", (Type: 0)
DEBUG: Grabbing hotkeys from keyboard '3' .
Enabled Device 1: "PixArt USB Optical Mouse", (Type: 0)
DEBUG: Grabbing hotkeys from keyboard '3' .
Enabled Device 2: "Virtual core XTEST pointer", (Type: 0)
Now 3 enabled devices.
DEBUG: Ungrabbed all Devices.
DEBUG: Hiding window.
DEBUG: got configure event

I have minimal knowledge regarding these things but If there's anything I can do to help, just ask.

**Comment by bk138** [comment]
For the Pause/Break issue: the default hotkey is F9.

Also, I'd need the debug output when you're clicking the menu entry for toggle pls.

**Comment by Jayce08** [comment]
As for the debug output when I clicked the toggle toggle painting option, it **shows nothing** as in no codes in the terminal. The last codes are DEBUG: trayicon activated which pops when trayicon is clicked. But as for the other option like the clear screen it works fine when clicked. (DEBUG : Cleared screen.)

When I installed Gromit-mpx, the default key for the toggle painting is the "Pause / Break " key. I have read somewhere that for Debian / Ubuntu specific, it uses the pause / break while in non-debian based distros it uses the F9 which is the real default key.

Maybe it has something to do with the pause / break key being the default in Debian / Ubuntu rather than the F9 key?

**Comment by bk138** [comment]
What version of raspbian with which desktop are you using?

**Comment by Jayce08** [comment]
I am using Raspbian Jessie at the moment (Haven't upgraded to Stretch) on Raspberry Pi 3. 

I have tried to install a gromit-mpk fork from maxchendt. In that version, _clicking_ the toggle painting works. Which means the problem doesn't lie on the raspbian version or which desktop I am using. (The only problem there is that you can see a gray icon in the taskbar instead of the gromit-mpx logo BUT that's a different topic.)

Nevertheless, your program works flawlessly so thank you for that and for assisting me. Thumbs up. :)

**Comment by bk138** [comment]
Can we close this issue then @Jayce08 ?
