### ISSUE TITLE
Gnome-shell 3.26.1 has no sys tray

### ISSUE THREAD

**Issue by russel** [bk138/gromit-mpx#47]
It seems that the sys tray has gone from gnome-shell 3.26.1. It doesn't affect the use of Gromit-MPX as I use it, but it does make the blurb about using it not up-to-date.

**Comment by bk138** [comment]
Then maybe a note should be added to the docs?

**Comment by russel** [comment]
I think so. I am headed off to PyConUK shortly so will have to delay doing a pull request till next week.
