### ISSUE TITLE
Using keyboard letters

### ISSUE THREAD

**Issue by moozer** [bk138/gromit-mpx#53]
Is it possible to make a config where e.g pressing the "b" key on the keyboard maps to drawing with blue?

something like 
```
"red Pen" = PEN (size=5 color="red");
"blue Pen" = "red Pen" (color="blue");

"Virtual core keyboard"[b] = "blue Pen";

```

**Comment by bk138** [comment]
Sure it is. Contributions are always welcome!

**Comment by bk138** [comment]
General update: issues with Gromit-MPX can now be funded at https://issuehunt.io/r/bk138/gromit-mpx

**Comment by bk138** [comment]
@moozer Do you want e.g. 'b' to select a specific tool or act as an additional modifier to Alt,Shift,Ctrl?

**Comment by bk138** [comment]
Tentatively closing as there's requested info missing. Feel free to re-open if there's news.
