### ISSUE TITLE
Update man page

### ISSUE THREAD

**Issue by jakevanderkolk** [bk138/gromit-mpx#54]
I saw that there is at least one argv option (-o to set opacity) that isn't documented in the man page. Would it be possible to update the man page to reflect this new usage and any others?

**Comment by bk138** [comment]
yes, it would be and indeed is possible.

**Comment by bk138** [comment]
@jakevanderkolk Would you like to help and add this to the man page?

**Comment by jakevanderkolk** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I only know what is in the existing man page; perhaps the person best suited to write the documentation would be the one who knows what is not documentation.
-----BEGIN PGP SIGNATURE-----
Version: ProtonMail
Comment: https://protonmail.com

wsBcBAEBCAAQBQJb1k67CRCLeqUQcLn+owAA8qQIAI4NKJgLO73kWSrPq0nd
xmH2DNV53w7S+sjQSI3ng/1UgdOY973CLvfPzGHmKsC0CN6hlPCRVOa6l86f
7qDhhA+fUcZUKr472ZxLqOcbZGIo5BafssbCkLU9gKgP9b88RXXn3h164j1P
6cd2c/RAjurMEHAeDz9hzUk5dslDXqpzoHnffULtFTw1EzkqbDfGntnCvfBt
yGoPlJLgQJ5eBTCn4gDV3MQVQXgsM7AWIxeic2zjQc8YJNTjpCCVLjecxxqK
uGE54HKO8L/avG+Mxwu/xnDUzREjk1+16ExpTdd7vwU4sUIAueJX+YV8Ldi2
WA7MwWAaXT7dQBgAfIUBxrg=
=jA6D
-----END PGP SIGNATURE-----
