### ISSUE TITLE
Multi-pointer not working, clarification needed

### ISSUE THREAD

**Issue by ElijahLynn** [bk138/gromit-mpx#59]
I have a X1 Yoga as well as a Lenovo ThinkVision, both are 10 point touch. Should I be able to draw with multiple fingers at the same time? If so, I can only use 1 finger and it isn't working. What steps should I take to debug multi-pointer not working?

**Comment by ElijahLynn** [comment]
Nice, gonna try this shortly, thank you!

**Comment by ElijahLynn** [comment]
I am going through the new documentation now and I think I misunderstood the functionality. I think it is aimed at multiple devices, not necessarily a multi-pointer device itself, which in this case is a 10 point touch device, with a single slave ID. Am I understanding this correctly? 

I attached the Wacom touch slave to the new master, but it still doesn't work with multiple fingers. I suspect that Gromit needs to somehow interpret those 10 touches coming from a single slave, is that right?

**Comment by bk138** [comment]
yes, it's aimed at multiple pointers as in pointing devices, not touch points. 

Am 21. November 2018 00:10:00 MEZ schrieb Elijah Lynn <notifications@github.com>:
>I am going through the new documentation now and I think I
>misunderstood the functionality. I think it is aimed at multiple
>devices, not necessarily a multi-pointer device itself, which in this
>case is a 10 point touch device, with a single slave ID. Am I
>understanding this correctly? 
>
>I attached the Wacom touch slave to the new master, but it still
>doesn't work with multiple fingers. I suspect that Gromit needs to
>somehow interpret those 10 touches coming from a single slave, is that
>right?
>
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/bk138/gromit-mpx/issues/59#issuecomment-440462011

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
