### ISSUE TITLE
~/.config/gromit-mpx.cfg keeps getting overwritten

### ISSUE THREAD

**Issue by ElijahLynn** [bk138/gromit-mpx#61]
Everytime I modify ~/.config/grommit-mpx.cfg and restart grommit-mpx it wipes my changes out. 

Version 1.3 on Arch.

**Comment by bk138** [comment]
As you can see in https://github.com/bk138/gromit-mpx/blob/a185c564fd94759190d6c9363c5a66b04abfd7a7/src/config.c#L125 gromit-mpx.cfg is only ever read, not written.

**Comment by ElijahLynn** [comment]
Hrm, I'll dig into this more. Something is writing to it, tested at least 3 times, maybe `strace` will shed some light here.

**Comment by ElijahLynn** [comment]
K, user error here. I was writing to the `~/.config/gromit-mpx.ini` file!
