### ISSUE TITLE
Excluding windows from drawing

### ISSUE THREAD

**Issue by rianadon** [bk138/gromit-mpx#62]
Hi there!

First of all I love the project. It's too fast and I've yet to run into any bugs.
I wanted to try to get an application to still be clickable while Gromit-MPX was in use. In other words, the mouse would draw lines while outside of that window but once inside stop drawing and interact with the window. Then once moved outside the window start drawing again.

Given the way Gromit works currently, which as I understand Gromit takes control of the mouse and consumes its events when drawing, preventing them from reaching windows underneath, would there be any easy way to implement this?

Thanks!

**Comment by bk138** [comment]
thanks for the props! excluding windows would be hard to implement, I suggest using a second mouse as we are -mpx after all 😉

**Comment by rianadon** [comment]
No problem! I should've added it's well maintained too. I envisioned making a toolbar (like Ardesia has) for adjusting the pen size and color, and was thinking maybe I could exclude that from the drawing area. However you're right; it's not too hard to use a combination of touchsceen / mouse to do controls and drawing separately. :smiley:
