### ISSUE TITLE
i3-wm + gromit-mpx + scrot --select

### ISSUE THREAD

**Issue by whoizit** [bk138/gromit-mpx#63]
can't launch `scrot --select` if gromit-mpx already launched. Any tips?
```
set $scr '~/screenshots'
bindsym --release $mod+Print exec scrot --select --exec 'mkdir -p $scr && mv $f $scr/'
bindsym --release $mod+Shift+Print exec scrot --exec 'mkdir -p $scr && mv $f $scr/'

bindsym --release $mod+Scroll_Lock exec gromit-mpx --active
bindsym --release $mod+Shift+Scroll_Lock exec gromit-mpx --quit
```

**Comment by whoizit** [comment]
I solve it without gromit-mpx
`bindsym --release $mod+Scroll_Lock exec scrot --select --exec 'mkdir -p $scr && mv $f $scr/ && gimp $scr/$f'`

**Comment by bk138** [comment]
Cool :-) Can be closed thus?

**Comment by zenny** [comment]
> I solve it without gromit-mpx
> `bindsym --release $mod+Scroll_Lock exec scrot --select --exec 'mkdir -p $scr && mv $f $scr/ && gimp $scr/$f'`



> can't launch `scrot --select` if gromit-mpx already launched. Any tips?
> 
> ```
> set $scr '~/screenshots'
> bindsym --release $mod+Print exec scrot --select --exec 'mkdir -p $scr && mv $f $scr/'
> bindsym --release $mod+Shift+Print exec scrot --exec 'mkdir -p $scr && mv $f $scr/'
> 
> bindsym --release $mod+Scroll_Lock exec gromit-mpx --active
> bindsym --release $mod+Shift+Scroll_Lock exec gromit-mpx --quit
> ```

@whoizit Confused what you solved?

Your "solution" is to disable the keybindings to start the gromit-mpx with mod+Scroll_Lock combo and replace that with the scrot screenshot tool.

Do you mean that you disabled the `gromit-mpx --active` option? I could not figure out both of the commands were invoked by i3 bindsym to mod+Scroll_Lock.

Thanks!
