### ISSUE TITLE
Disable startup tooltip in conifg

### ISSUE THREAD

**Issue by sammerry** [bk138/gromit-mpx#64]
When run from the command-line there is no way to disable the popup tool tip. The `show again on startup` checkbox is ignored.

Is there any way to disable this from the config file?

**Comment by bk138** [comment]
You have to quit via the menu or the hotkey or edit the ini file (https://github.com/bk138/gromit-mpx/blob/master/src/config.c#L372)

**Comment by bk138** [comment]
HTH, please close if it does.

**Comment by sammerry** [comment]
quitting via menu and hot key didn't work on my set up but manually creating `~/.config/gromit-mpx.ini` and adding

```
[default]
show_intro_on_startup=false
```
removes the tool tip.

Thanks!

**Comment by bk138** [comment]
would be interesting to know why it didn't work. was the .config dir not there?
