### ISSUE TITLE
Add functionality to draw straight lines

### ISSUE THREAD

**Issue by TravelTrader** [bk138/gromit-mpx#67]
#44 is similar but I want to open it as a feature-request.
Because it would be a great possibility to **add lines to Gromit**.

I would help with the code if there is interest and support because I'm not a graphics programmer.

**Pressing a key to start a line** in the same color like the "freehand" option and **hold it down until the end point of the line** is reached. Simple like the other tools but a new feature.

_What do you think? Why not?_

**Comment by bk138** [comment]
Some thoughts:

* Best approach probably is to start bottom up and add a new "tool" in addtion to PEN, ERASER and RECOLOR, see https://github.com/bk138/gromit-mpx/blob/master/src/config.c#L152 and https://github.com/bk138/gromit-mpx/blob/master/src/gromit-mpx.h#L57
* This could be used to define a new paint context that the programm could interpret specifically as a straight line in the button down and up handlers.

**Comment by bk138** [comment]
General update: issues with Gromit-MPX can now be funded at https://issuehunt.io/r/bk138/gromit-mpx

**Comment by Cybernetic1** [comment]
I'd like to contribute.  Which file(s) and where abouts should I start looking?  Why is such a simple feature taking so long to implement?  Thanks :)

**Comment by bk138** [comment]
> I'd like to contribute. Which file(s) and where abouts should I start looking? Why is such a simple feature taking so long to implement? Thanks :)

Thanks for your interest! See my comments [here](https://github.com/bk138/gromit-mpx/issues/104#issuecomment-991738242). This simple feature takes so long to implement because of lack of time, at least on my side :-)

**Comment by borys-upco** [comment]
Hi. Is there any chance to push this feature and get it implemented?

**Comment by bk138** [comment]
> Hi. Is there any chance to push forward this feature and get it implemented?

Yes, one might file a "bounty" via https://issuehunt.io/r/bk138/gromit-mpx/issues/67 so some interested party feels incentivized to implement this; basically anyone, not necessarily me.

The other option would be to hire me to spend paid work time on this feature, that'd be via https://christianbeier.net.

The last option is to simply wait it out, it's on [my agenda for the project](https://github.com/bk138/gromit-mpx/milestones), but I'm currently very busy with customers and family, so no better ETA on the horizon than "some time in the future".

**Comment by borys-upco** [comment]
@bk138 Perfect it is not urgent, I can live without it. Maybe I will motivate my self and learn c and gtk.
It is hard from the JS and C# World.
