### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by ahangarha** [bk138/gromit-mpx#68]
Is there any way to run / compile Gromit for Windows?

**Comment by bk138** [comment]
In principle yes, as [X11 for Windows](https://en.wikipedia.org/wiki/X_Window_System#Implementations) and [GTK+ for Windows](https://www.gtk.org/download/windows.php) exist, but they're probably a hell lotta pitfalls.

**Comment by bk138** [comment]
Tentatively closing this, feel free to re-open if issue persists and relates to Gromit-MPX.
