### ISSUE TITLE
Compton gromit-mpx shadows

### ISSUE THREAD

**Issue by akemrir** [bk138/gromit-mpx#69]
Hi, 
I am using compton as desktop composition manager.
When I use gromit-mpx shadow appears on whole paint-able screen.

I can't check class of this window with xprop.
Which window class I should use to exclude gromix paint area?

**Comment by bk138** [comment]
You might have to look into the source code, no idea. Sorry :-) 

I might be able to add a certain property to the window, but don't know which.

**Comment by bk138** [comment]
Tentatively closing this, feel free to re-open if issue persists and and/or you have new info.
