### ISSUE TITLE
rgb-colors do not appear as specified

### ISSUE THREAD

**Issue by ghistes** [bk138/gromit-mpx#70]
Hi,

I am using gromit-mpx 1.3.1 on Debian testing with i3.
When specifying either

"yellow Pen" = PEN (size=5 color="yellow");

or

"yellow Pen" = PEN (size=5 color="#FFFF00");

I do not get the desired yellow colour, but rather some sort of greenish/brownish yellow.

I do not understand where this behaviour comes from, but I've found some search results that suggest cairo using a different color-model internally, maybe this is relevant (but I really have no clue).

I would be happy to find a workaround to specify the color I want to use.

**Comment by bk138** [comment]
would be nice if you posted a complete config file :-9

**Comment by ghistes** [comment]
The issue appears on my system even in the default configuration (i.e. yellow is not really yellow).

But I am using:

[General]
ShowIntroOnStartup=false

"red Pen" = PEN (size=5 color="red");
"blue Pen" = "red Pen" (color="blue");
"yellow Pen" = PEN (size=5 color="#FFFF00");
"green Marker" = PEN (size=6 color="green" arrowsize=1);

"Eraser" = ERASER (size = 75);

"default" = "blue Pen";
"default"[SHIFT] = "red Pen";
"default"[CONTROL] = "yellow Pen";
"default"[2] = "green Marker";
"default"[Button3] = "Eraser";

**Comment by bk138** [comment]
The file contents you posted are a mix of the .ini file and the .cfg file, this can't work.

**Comment by ghistes** [comment]
Sorry for being unclear.

 gromit-mpx.ini:

[General]
ShowIntroOnStartup=false

gromit-mpx.cfg:

"red Pen" = PEN (size=5 color="red");
"blue Pen" = "red Pen" (color="blue");
"yellow Pen" = "red Pen" (color="yellow");
"green Marker" = PEN (size=6 color="green" arrowsize=1);

"Eraser" = ERASER (size = 75);

"default" = "blue Pen";
"default"[SHIFT] = "red Pen";
"default"[CONTROL] = "yellow Pen";
"default"[2] = "green Marker";
"default"[Button3] = "Eraser";

But as I said, the problem is (at least on two of my machines) visible even in the default configuration.

When trying to use the yellow pen the colour painted is not really the yellow one would expect - regardless of the colour being specified as "yellow" or as an rgb-code.

**Comment by bk138** [comment]
Might be some issue with your environment. Try to: 

1. find a environment where all works
1. find out what's different to your setup
1. eliminate one difference, check if issue persists
1. go on with 3.

**Comment by ghistes** [comment]
I tried it with gnome-shell and there I get the colours I expect.
I see this problem with i3 on two machines, so it seems to be i3 related - what gromit-magic could be WM-dependent?

But many thanks, this is probably not a gromit issue...

**Comment by bk138** [comment]
> I tried it with gnome-shell and there I get the colours I expect.
> I see this problem with i3 on two machines, so it seems to be i3 related - what gromit-magic could be WM-dependent?

Nothing actually. Both WMs are on X11?

**Comment by ghistes** [comment]
Both WMs are on X11 and even on the same machine.
When I run a gnome-shell session everything is fine.
When I run a i3 session (as I normally do) the color is off.
But another application (firefox say) display this color ok.
So what I see (on two machines) is that with i3 firefox display #ffff00 as bright yellow as expected but when configuring this color with gromit it paints a greenish color.
No idea where that problem might come from...

**Comment by bk138** [comment]
Gromit-MPX uses Cairo for drawing. You might be able to use a sample from their website and repro the issue.

**Comment by bk138** [comment]
Tentatively closing this, feel free to re-open if issue persists and relates to Gromit-MPX.
