### ISSUE TITLE
color selector

### ISSUE THREAD

**Issue by ChameleonScales** [bk138/gromit-mpx#71]
Changing colors is currently a little cumbersome (edit the config file, restart gromit-mpx).
This is especially problematic when you want to use gromit-mpx to make design decisions by comparing a color against another (e.g on top of an image), without having to open an image editor.

Having a color selector (similar to gcolor2) to change the main color would make it a lot easier.
The way I see it implemented is as a popup window which you could open from the menu.

**Comment by bk138** [comment]
This will be tackled via #110.
