### ISSUE TITLE
Some system-tray menu items not working (Kubuntu)

### ISSUE THREAD

**Issue by malnaanah** [bk138/gromit-mpx#72]
I use Kubuntu (19.04) and the following system-tray menu items do not work:
1- Toggle Painting  (it does not work when selecting from the menu but works when pressing F9)
2- Thicker line (and thinner line): no effect when selecting them on the drawn lines, also it is not possible to choose them when painting is active.

Regards,

**Comment by bk138** [comment]
Would you be so nice and specify the version in use as well?

**Comment by malnaanah** [comment]
It is 1.3 (I think it is the latest)

**Comment by bk138** [comment]
@malnaanah do the keyboard shortcuts work?

**Comment by malnaanah** [comment]
The following system-tray menu items do not work:
1- Toggle Painting: ( The shortcut F9 is working)
2- Thicker Lines" (Has no shortcut and cant be selected if Painting is active)
3- Thinner Line: (Has no shortcut and cant be selected if Painting is active)
4- Bigger Opacity: (Has no shortcut and cant be selected if Painting is active)
5- Lesser Opacity: (Has no shortcut and cant be selected if Painting is active)

Other options activate correctly through the menu and the shortcut, but the undo option most of the time leaves black lines instead of erasing them.

I use Kubuntu 18.04 and gr0mit-mpx version 1.3
video card: 00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

**Comment by bk138** [comment]
Line thickness and opacity cannot be modified while painting right now.

**Comment by malnaanah** [comment]
Even changing line thickness and opacity before painting will not change a thing.

**Comment by bk138** [comment]
@malnaanah Does this happen with Kubuntu 20.04 as well?

**Comment by bk138** [comment]
"thinner" and "thicker" works for me on Kubuntu 20.04, "toggle painting" _not_.

**Comment by bk138** [comment]
https://stackoverflow.com/questions/39480064/button-press-event-and-gtk-frame

**Comment by bk138** [comment]
https://github.com/electron/electron/issues/6773
