### ISSUE TITLE
Is it possible to redesign the interface to be more like Ardesia.

### ISSUE THREAD

**Issue by malnaanah** [bk138/gromit-mpx#74]
It will be really a good thing if the design of the UI is changed to be more like Ardesia .

The current UI is very limited and not user-friendly, also, many features are not working, such as changing the thickness and the transparency of the marker.

Ardesia, on the other hand, had a friendly interface and many features that needs to be in Gromit-mpx. Unfortunately Ardesia is not installable or functioning in Ubuntu 18.04 and higher.

![ardesia](https://user-images.githubusercontent.com/45626803/72425192-f34d4580-378f-11ea-8c89-6948e27b31a2.png)

**Comment by bk138** [comment]
Contributions welcome!

**Comment by zenny** [comment]
I prefer current mode with keyboard shortcuts to get away with distractions.

However, an option to have a sidebar like in ardesia could be a good addition for those visually-savvy ones. ;-)

Just my two cents.

Cheers,
/z

**Comment by zenny** [comment]
> It will be really a good thing if the design of the UI is changed to be more like Ardesia .
> 
> The current UI is very limited and not user-friendly, also, many features are not working, such as changing the thickness and the transparency of the marker.
> 
> Ardesia, on the other hand, had a friendly interface and many features that needs to be in Gromit-mpx. Unfortunately Ardesia is not installable or functioning in Ubuntu 18.04 and higher.
> 
> ![ardesia](https://user-images.githubusercontent.com/45626803/72425192-f34d4580-378f-11ea-8c89-6948e27b31a2.png)

@malnaanah I do not agree with your opinion about user friendliness. Once you are in the *nix space, you should have to have a respect for basic tenets of the *nix principles of KISS and Less is More. 

The best part of the gromit-mpx is that its functions are simply mapped to combinations of keyboard and mouse buttons. Remembering about 10 combinations should not be difficult to someone who is using any *nix platforms. User-friendliness is not about multiple visible icons, but how is it easy to implement in real life (Bloom's taxonomy). Think about the numbers of buttons in walkman and ipod and decide yourself which was more user-friendly?

Just my two cents!

Cheers,
/z

**Comment by bk138** [comment]
Basically: no. But see #110 for what we will do.
