### ISSUE TITLE
[Feature Request] Map annotation colors to mouse buttons

### ISSUE THREAD

**Issue by zenny** [bk138/gromit-mpx#76]
Hi,

@bk138 The application is AWESOME. Yet I find a typical limitation as stated below.

How can one map annotation colors limited to mouse buttons because presenters in real scenario are provided only with airmouse (gravity mouse) these days (like in the notorious TED talks)?

Any tips appreciated!

Cheers,
/z

**Comment by bk138** [comment]
Hi @zenny I don't quite understand what kind of feature you are requesting. Something like Button1==red, Button2==green?

**Comment by zenny** [comment]
> Hi @zenny I don't quite understand what kind of feature you are requesting. Something like Button1==red, Button2==green?

You got it. Assign certain buttons in the gravity (air) mouse to change the colors of the annotations and shapes. Yoho!

**Comment by bk138** [comment]
> > Hi @zenny I don't quite understand what kind of feature you are requesting. Something like Button1==red, Button2==green?
> 
> You got it. Assign certain buttons in the gravity (air) mouse to change the colors of the annotations and shapes. Yoho!

Isn't that what we [already have](https://github.com/bk138/gromit-mpx/blob/master/data/gromit-mpx.cfg)? Button 1 red, button 2 green.

**Comment by bk138** [comment]
Tentatively closing this, feel free to re-open if my answer above doesn't solve the issue.
