### ISSUE TITLE
Hotkeys not working Linux Mint 19.3, XFCE

### ISSUE THREAD

**Issue by koketti** [bk138/gromit-mpx#77]
Hi,
at my system (Linux Mint 19.3; xfce), the hotkeys like F9 are not working. 

gromit-mpx version: 1.2-2
Kernel version: 5.3.0-42
Xorg version: 1.20.5
wayland-protocol : 1.13-1

Is there a way to enable the hotkeys?
Regards

**Comment by bk138** [comment]
Please start from a terminal using `gromit-mpx -d` and post the output :-)

**Comment by koketti** [comment]
Tool name: "Eraser|@0           ": Eraser,  width:  75, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "default|@1          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(0,0,255)
Tool name: "default|@2          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,255,0)
Tool name: "red Pen|@0          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "default|B0          ": Pen,     width:   6, minwidth:   1, arrowsize: 1,00, color: rgb(0,128,0)
Tool name: "default|@0          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "green Marker|@0     ": Pen,     width:   6, minwidth:   1, arrowsize: 1,00, color: rgb(0,128,0)
Tool name: "default|D0          ": Eraser,  width:  75, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "yellow Pen|@0       ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,255,0)
Tool name: "blue Pen|@0         ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(0,0,255)
Supported backends: x11 wayland 
Using backend: x11
DEBUG: Ungrabbed all Devices.
DEBUG: Grabbing hotkeys from keyboard '3' .
Enabled Device 0: "Virtual core pointer", (Type: 0)
DEBUG: Grabbing hotkeys from keyboard '3' .
Enabled Device 1: "Dell Dell Wired Multimedia Keyboard Mouse", (Type: 0)
DEBUG: Grabbing hotkeys from keyboard '3' .
Enabled Device 2: "Logitech USB-PS/2 Optical Mouse", (Type: 0)
DEBUG: Grabbing hotkeys from keyboard '3' .
Enabled Device 3: "AlpsPS/2 ALPS DualPoint TouchPad", (Type: 6)
DEBUG: Grabbing hotkeys from keyboard '3' .
Enabled Device 4: "AlpsPS/2 ALPS DualPoint Stick", (Type: 7)
DEBUG: Grabbing hotkeys from keyboard '3' .
Enabled Device 5: "Virtual core XTEST pointer", (Type: 0)
Now 6 enabled devices.
DEBUG: Ungrabbed all Devices.
DEBUG: Hiding window.
DEBUG: got configure event

**Comment by bk138** [comment]
Please try again with current master, I've added some more verbose debug output. Also, please try changing the hotkeys as per https://github.com/bk138/gromit-mpx#how-to-use-it

**Comment by koketti** [comment]
Hi, sorry for delay,
I don't understand the meaning of "current master"? Do you mean "root"?
I've tried to change the hotkeys with the --key option: 
gromit-mpx --key "F9". But there is no effect.
Was the command correct?

**Comment by bk138** [comment]
Current master means to checkout the source and build it yourself. If this is not an option, you might want to change some other parts of your setup, like desktop environment. The syntax is correct.

**Comment by phiddr** [comment]
I have the same problem in Xubuntu 19.10. Hotkeys work when I have focus on Gromit window. They do not work elsewhere. The program cannot capture keys so that other applications cannot use them. In general, it does not capture keys whenever I am outside the Gromit window.  Changing keys using "gromit-mpx --key" does not wok (changed key works in Gromit window, but not elsewhere). I installed the repository version (version 1.3).

**Comment by bk138** [comment]
You're both using XFCE it seems. Does it work when changing to another desktop environment?

**Comment by phiddr** [comment]
Thank you for your immediate response. I could only test it with Lubuntu 19.10, where it works fine. So, the problem probably has to do with XFCE.

**Comment by bk138** [comment]
Only found [this](https://forum.xfce.org/viewtopic.php?id=12164) in a short google attack. My guess is that some part of XFCE grabs the keys. Only the function keys?

**Comment by phiddr** [comment]
No, the problem is with all combination of keys.

**Comment by phiddr** [comment]
I'm sorry, I was wrong about my last statement. It indeed works for other keys (e.g. I used w). So, the problem appears only with function keys.

**Comment by phiddr** [comment]
I also noticed another problem. Running gromit-mpx --key "Control_R" sets the key to be Control and not Control+R.

**Comment by bk138** [comment]
> I also noticed another problem. Running gromit-mpx --key "Control_R" sets the key to be Control and not Control+R.

This is not supposed to work. You can only specify single keys, not combos.

**Comment by junrrein** [comment]
I'm also hitting this problem, but as @phiddr, this happens with some keys, but not others. I'm using Gnome 3.34 on Fedora 31 and Grommit on commit cc85db2f23c86b9fb608598a738a9b8ae2902e6c.

Keys that work for me in the F{1-12} range: F3, F4, F5, F7, F8

Below I'm posting the output of `gromit-mpx --debug` for a key that works and for one that doesn't. In both cases what I'm doing is:

* Open Gromit
* Switch to another window (since the key grab always works on the window spawned by Gromit)
* Use the hotkey (or try to)
* Draw a line
* Use the hotkey again to disable "draw" mode
* Close the app by using `Ctrl+C`

For a key that works (F7): https://gist.github.com/junrrein/1fc2bfa4e1276aa615c584c729464445

For a key that doesn't (F12): https://gist.github.com/junrrein/c9031e2fa7766d1cf2936c1cfb21aab4

As an aside, even with this issue, Gromit is working great. Thanks a lot!

**Comment by bk138** [comment]
I reckon it's got to do with the DE having grabbed certain keys. For me, F10 does not work. I've added some diagnostics with d9b1627c92d3a96b96a048d972da229ec36bc0ce.

**Comment by junrrein** [comment]
Running the test again using 0c9e6924ab5feef64f23ceeb837bddc0cba95dfb for a key that fails (F12, set via the config file):

```
❯ gromit-mpx --debug
Tool name: "yellow Pen|@0       ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,255,0)
Tool name: "default|@2          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,255,0)
Tool name: "blue Pen|@0         ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(0,0,255)
Tool name: "red Pen|@0          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "Eraser|@0           ": Eraser,  width:  75, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "default|@0          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "default|@1          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(0,0,255)
Tool name: "default|D0          ": Eraser,  width:  75, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "green Marker|@0     ": Pen,     width:   6, minwidth:   1, arrowsize: 1,00, color: rgb(0,128,0)
Tool name: "default|B0          ": Pen,     width:   6, minwidth:   1, arrowsize: 1,00, color: rgb(0,128,0)
Supported backends: x11 wayland 
Using backend: x11
DEBUG: Ungrabbed all Devices.
DEBUG: Grabbing hotkeys 'F12' and 'F8' from keyboard '3' .
ERROR: Grabbing hotkey from keyboard device 3 failed.
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.
DEBUG: Ungrabbed all Devices.
DEBUG: Hiding window.
DEBUG: got configure event
^[[24~^[[24~^C⏎ 
```

**Comment by farbodahm** [comment]
I had same problem in Xubuntu 20.04 with Xfce 4.14, which changing hotkey to `w` (as @phiddr mentioned) solved the problem.

**Comment by Popolon** [comment]
Same problem with Arch Linux, XFCE 4.14. It works with only with key 'z', as I am on a french AZERTY keyboard, it match the english QWERTY w hardware key. I believe the hardware keykode is used instead of system managed input ? It really limit the usage of the tool, if this key is needed at the same time.

**Comment by Popolon** [comment]
I was able to make azertyuiop work (the whole first range of letters ) working too with an error at launch with this key, 'w' can't work on my system, nor special key i rarely use.
on the second line (qsdfghjklm), q, d don't work, s, f, g, h, j, k, l, m  work 
on the third line (<wxcvbn) w don't work, x, and '' works, I an't stop it ^^.
<pre>
$ gromit-mpx -d -k 'o'
Could not open /home/popolon/.config/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Could not open /etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Supported backends: x11 wayland 
Using backend: x11
DEBUG: Ungrabbed all Devices.
DEBUG: Grabbing hotkeys 'o' and 'F8' from keyboard '3' .
ERROR: Grabbing undo key from keyboard device 3 failed.
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.
<Pre>

**Comment by bk138** [comment]
It's got to do with XFCE, other desktop environments work fine...

**Comment by Popolon** [comment]
so c worked, but i was not able to ctrl-c then, the other letters of the range worked, but so only standard characters keys work.

**Comment by Popolon** [comment]
I also use stardict (GTK+) on XFCE, it has hot keys (combination of keys, not only one key), to display translation of a select word anywhere on screen, and it works just fine with XFCE, perhaps that it's method for grabbing is more generic ? I'm not sure I tested it on another DE ?

**Comment by Popolon** [comment]
the sources used are available here, https://sourceforge.net/projects/stardict-4/files/3.0.6/
hotkeys are managed in dict/src/tomboykeybinder.(cpp|h).
There is also an application preferences, that contains a hotkeyeditor;(cpp|h), in the same directory.

**Comment by Popolon** [comment]
It is based on X11/XKBlib.h (x11_iskeyspressed.cpp), so probably only works on X11 (at least if X11 libs are not loaded in wayland), where your application use GDK and can work on wayland too.

**Comment by nanotube** [comment]
just wanted to chime in, i am experiencing same issue here, using a fresh install of xubuntu 20.04. 
the default f9 key doesn't work, but running with "--key w" works.

**Comment by Popolon** [comment]
As said the author a bug should be opened on XFCE...

**Comment by nanotube** [comment]
Opened XFCE issue here: https://gitlab.xfce.org/xfce/xfwm4/-/issues/445

**Comment by nanotube** [comment]
See the response on the XFCE issue. 

gromit and xfce now use the same mechanism to grab the keyboard shortcut, so they cannot conflict, and xfce grabs ctl-f1-f12 (switch to workspace 1-12) and alt-f9 (minimize window) by default. 

not sure what the best way to avoid the conflicts, perhaps allow more detailed configuration of gromit keys. e.g. if one could set F9 to toggle painting, but F8 to toggle vis, and F7 to quit, one could avoid conflicts with window manager shortcuts, while still using F keys and thus not conflicting with normal typing operations.?

**Comment by bk138** [comment]
> not sure what the best way to avoid the conflicts, perhaps allow more detailed configuration of gromit keys. e.g. if one could set F9 to toggle painting, but F8 to toggle vis, and F7 to quit, one could avoid conflicts with window manager shortcuts, while still using F keys and thus not conflicting with normal typing operations.?

Distributing the functions across different hotkeys will be a lot of work - what about detecting XFCE and using another default hotkey? This would be way easier. Don't know what would be a good choice though. My laptop, for instance, has no Pause key, but home Home, End, Insert, Del on the upper row next to the function keys. Suggestions welcome!

**Comment by artofit** [comment]
continuation of issue 105: [https://github.com/bk138/gromit-mpx/issues/105#issuecomment-728828753](url)
gromit-mpx, just got updated from AUR 1.3.31.r40.g4b77135-1 to  1.3.1.r41.g5ea63fa-1
gromit-mpx>about displays version 1.4

If I do understand correctly, gromit-mpx
>bk138: You can only specify single keys, not combos
I do not see this in gromit-mpx>manual, please update.

From issue 77:

> 4. I'm not sure of what you refer as "the workarounds in #77?"
The workaround is: define another hotkey that's not grabbed by XFCE, see #77 (comment).

So if links refers to gromit-mpx --key "Control_R":
it fails for me:

$ gromit-mpx --key "Control_R"
Could not open user config /home/toshpc/.config/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Could not open Flatpak config /app/etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Could not open system config /etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
No usable config found, leaving tools unconfigured!

(gromit-mpx:5461): libappindicator-CRITICAL **: 12:15:48.942: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
ERROR: Grabbing undo key from keyboard device 3 failed.
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.

(gromit-mpx:5461): libappindicator-CRITICAL **: 12:15:50.993: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed

(gromit-mpx:5461): Gdk-CRITICAL **: 12:15:51.200: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by bk138** [comment]
@artofit please have a try with `gromit-mpx --key q --undo-key w`, for instance.

**Comment by artofit** [comment]
FYI: Azerty keyboard 102 keys

$ gromit-mpx --key q --undo-key w
Could not open user config /home/toshpc/.config/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Could not open Flatpak config /app/etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Could not open system config /etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
No usable config found, leaving tools unconfigured!

(gromit-mpx:13087): libappindicator-CRITICAL **: 13:50:40.964: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.

(gromit-mpx:13087): libappindicator-CRITICAL **: 13:50:40.965: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed

(gromit-mpx:13087): Gdk-CRITICAL **: 13:50:41.204: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by bk138** [comment]
> FYI: Azerty keyboard 102 keys
> 
> $ gromit-mpx --key q --undo-key w
> Could not open user config /home/toshpc/.config/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
> Could not open Flatpak config /app/etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
> Could not open system config /etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
> No usable config found, leaving tools unconfigured!
> 
> (gromit-mpx:13087): libappindicator-CRITICAL **: 13:50:40.964: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
> Enabled Device 0: "Virtual core pointer", (Type: 0)
> Now 1 enabled devices.
> 
> (gromit-mpx:13087): libappindicator-CRITICAL **: 13:50:40.965: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
> 
> (gromit-mpx:13087): Gdk-CRITICAL **: 13:50:41.204: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
> 
> **fails also with**
> $ gromit-mpx --key s --undo-key x
> $ gromit-mpx --key a --undo-key z

From the logs, it looks like you should be able to toggle using q/w @artofit. What happens if you hit q in this case?

**Comment by artofit** [comment]
Well it works, sorry, but seeing the "CRITICAL" I didn't try.

$ gromit-mpx --key Pause --undo-key Print
also works, I recommand to update the manual

Now regarding, /usr/etc/gromit-mpx/gromit-mpx.cfg
A/ I sudo updated to, but gromix-mpx does not default to q/w
# Uncomment to set Hot key and/or Undo key to a custom value
HOTKEY = "q";
UNDOKEY = "w";

B/ I don't manage to get the other colours:
"default" = "red Pen";						
"default"[SHIFT] = "blue Pen";					
"default"[CONTROL] = "yellow Pen";				
"default"[2] = "green Marker";					
"default"[Button3] = "Eraser";

**Comment by bk138** [comment]
> Now regarding, /usr/etc/gromit-mpx/gromit-mpx.cfg
> A/ I sudo updated to, but gromix-mpx does not default to q/w

As that's unrelated to this issue here, let's move over to https://gitter.im/gromit-mpx/community - quick hint: Gromit-MPX does not read /usr/etc/gromit-mpx/gromit-mpx.cfg.

**Comment by artofit** [comment]
OK, I'm do that, I see that there has been a new 1.3.1.r43 AUR release

**Comment by manujchandra** [comment]
Running from Fedora 35 XFCE producing the following output:

```flatpak run net.christianbeier.Gromit-MPX
Gtk-Message: 14:56:16.050: Failed to load module "xapp-gtk3-module"
Detected XFCE, changing default hot keys to 'Home' and 'End'
Using user config /home/manuj/.var/app/net.christianbeier.Gromit-MPX/config/gromit-mpx.cfg

(gromit-mpx:2): libappindicator-CRITICAL **: 14:56:16.125: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.

(gromit-mpx:2): libappindicator-CRITICAL **: 14:56:16.126: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed

(gromit-mpx:2): Gdk-CRITICAL **: 14:56:16.383: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

It says 

**Detected XFCE, changing default hot keys to 'Home' and 'End'**

and does not read the keys from config file, even though it says its using it.

**Comment by bk138** [comment]
@manujchandra can you provide some details on what you expect and what actually happens?

**Comment by manujchandra** [comment]
@bk138 I am using the following [config file](https://github.com/magnacore/Productivity-Tools/blob/master/Linux/config/gromit-mpx.cfg)

I expected the Hotkey to get changed to F9 and Undo Key to F8.

But its still Home and End.

I am using Flatpak version 1.4.

**Comment by bk138** [comment]
@manujchandra please note that the message says *default* hotkeys, it does not override what you might have configured (https://github.com/bk138/gromit-mpx#configuration). Please also note that you might not be able to configure  F9 and F8 at all on XFCE, see https://github.com/bk138/gromit-mpx#potential-problems
