### ISSUE TITLE
Adjust the minwidth to other values

### ISSUE THREAD

**Issue by dual3zw** [bk138/gromit-mpx#85]
Is it possible to adjust the minwidth to other values? I have an XP Pen Tablet and I would like to write with the line width between 2 and 3, for example.

**Comment by bk138** [comment]
You simply change the `size` of the tool in the [config file](https://github.com/bk138/gromit-mpx/blob/dd50fcfaa05277484aa81b4603a992fb17f76234/data/gromit-mpx.cfg#L9)

**Comment by dual3zw** [comment]
Does not work. Changing the size affects only the maximum stroke width and not the minimum. See image: https://drive.google.com/file/d/1wd7Yt1LqTrZWQQMTUL85eNPq-PbMBtDA/view?usp=sharing
What I need is for the size to be 3 and the minwidth to be 2.

**Comment by bk138** [comment]
See bb51710f4f3371480030ae7f9d6da91a1f37e6ea

**Comment by dual3zw** [comment]
Oh man, thanks! It works! Now I'm going to read the documentation to try to activate the pen button like an eraser.
