### ISSUE TITLE
Palm detection / Pen only input

### ISSUE THREAD

**Issue by Maralai** [bk138/gromit-mpx#86]
Detect a palm and ignore drawing points where it makes contact with the screen.

**Is your feature request related to a problem? Please describe.**
While using a stylus on the screen if I place my palm down to naturally write it detects the first contact points of my palm, this usually results in short strokes being added to the canvas where the palm is.

**Describe the solution you'd like**
I would like if the palm of the hand to be ignored or a feature that only allows for explicitly pen input.

**Describe alternatives you've considered**
Raising my hand in an awkward position to write in to ensure only the tip of the pen is engaged.

**Additional context**
I am using an Asus laptop running Ubuntu with a Bamboo Ink Plus. 
The laptop screen is touch and pen-enabled.

**Comment by Maralai** [comment]
Just another note, if I can get the eraser to work there is no problem the eraser can't solve. :P

**Comment by Maralai** [comment]
I have the eraser working and am liking this app! I tried to explicitly assign input from the pen by revising the cfg file from `default` to specifying my input `ELAN Touchscreen Pen (0)` however the input from any other device is still being registered. Is there a default I can override?

**Comment by bk138** [comment]
I just played around a bit and ended up with this hack:
```
"no Pen" = PEN (size=0);
"default" = "no Pen";
```

Not a proper fix but it works :-) For me. For you as well?

**Comment by Maralai** [comment]
Beautiful! This is a totally acceptable hack!
