### ISSUE TITLE
Launch straight to system tray

### ISSUE THREAD

**Issue by Maralai** [bk138/gromit-mpx#88]
It would be great to add a 'do not prompt again' feature for the starting dialog and toast that displays when the app is opened. I am now familiar with the features and do not need it to prompt me.

**Describe the solution you'd like**
I just want the app to launch and be ready without dialogs and prompts. :)

**Comment by bk138** [comment]
You simply have to quit via the menu's 'quit' to have the do-non-show-again take effect.

![Bildschirmfoto von 2020-05-17 19-00-37](https://user-images.githubusercontent.com/80450/82154825-d70e0200-9870-11ea-8ee5-d5fff02ef953.png)

**Comment by Maralai** [comment]
Good to go!
