### ISSUE TITLE
Disable pen pressure sensitivity

### ISSUE THREAD

**Issue by TheRawMeatball** [bk138/gromit-mpx#92]
I use a pen, and I think it would be nice if pressure sensitivity was toggleable, because, my lines are often inconsistent because of it.

**Comment by pn2** [comment]
I think an equivalent and possibly more flexible solution would be to allow for a maxsize parameter. To keep width constant, one could set minsize and maxsize to the same value.

**Comment by bk138** [comment]
Closed by 7adf741a1db131140c1155077d13c507560d16aa
