### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ltratt** [bk138/gromit-mpx#94]
Hello! Might it be possible to make a new release of gromit-mpx soon? I've packaged it up for OpenBSD, but the last release doesn't include fixes like the hotkeys-fix, so it's not as useful as I hoped. It would be great to have a new formal release so that users can get all the latest goodies!

**Comment by bk138** [comment]
Hi! Are you able to use a `1.3+<somecommit>` version like https://github.com/bk138/gromit-mpx/archive/7c83680253929e5bec4b882b763704653a679196.zip? There's still some [TODOs for 1.4](https://github.com/bk138/gromit-mpx/milestone/4)

**Comment by ltratt** [comment]
> Are you able to use a 1.3+<somecommit> version

I did a sort-of hacked version of this, but it's not ideal, because it's not obvious when the version number has increased/decreased. Perhaps a halfway house is a 1.3.1 release or something? I do appreciate that this is me being greedy!

**Comment by bk138** [comment]
Only because you asked so nicely ;-) : https://github.com/bk138/gromit-mpx/releases/tag/1.3.1

Do OpenBSD ports have metadata related to project support/donations? If so, please add the links from the README there :-)

**Comment by ltratt** [comment]
Thanks so much for this -- it really is much appreciated!
