### ISSUE TITLE
Unable to launch 

### ISSUE THREAD

**Issue by airbete** [bk138/gromit-mpx#95]
Master 8d55271 on Fedora 32

`./gromit-mpx -d`

Tool name: "yellow Pen|@0       ": Pen,     width:   5, minwidth:   1, arrowsize: 0.00, color: rgb(255,255,0)
Tool name: "default|@2          ": Pen,     width:   5, minwidth:   1, arrowsize: 0.00, color: rgb(255,255,0)
Tool name: "blue Pen|@0         ": Pen,     width:   5, minwidth:   1, arrowsize: 0.00, color: rgb(0,0,255)
Tool name: "red Pen|@0          ": Pen,     width:   5, minwidth:   1, arrowsize: 0.00, color: rgb(255,0,0)
Tool name: "Eraser|@0           ": Eraser,  width:  75, minwidth:   1, arrowsize: 0.00, color: rgb(255,0,0)
Tool name: "default|@0          ": Pen,     width:   5, minwidth:   1, arrowsize: 0.00, color: rgb(255,0,0)
Tool name: "default|@1          ": Pen,     width:   5, minwidth:   1, arrowsize: 0.00, color: rgb(0,0,255)
Tool name: "default|D0          ": Eraser,  width:  75, minwidth:   1, arrowsize: 0.00, color: rgb(255,0,0)
Tool name: "green Marker|@0     ": Pen,     width:   6, minwidth:   1, arrowsize: 1.00, color: rgb(0,128,0)
Tool name: "default|B0          ": Pen,     width:   6, minwidth:   1, arrowsize: 1.00, color: rgb(0,128,0)
Supported backends: x11 wayland 
Using backend: x11
DEBUG: Ungrabbed all Devices.

(gromit-mpx:2422927): GLib-GObject-WARNING **: 20:27:10.840: g_object_get_is_valid_property: object class 'GdkX11DeviceCore' has no property named 'device-id'

(gromit-mpx:2422927): Gdk-ERROR **: 20:27:10.840: The program 'gromit-mpx' received an X Window System error.
This probably reflects a bug in the program.
The error was 'XI_BadDevice (invalid Device parameter)'.
  (Details: serial 218 error_code 129 request_code 131 (XInputExtension) minor_code 48)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)

**Comment by bk138** [comment]
Please provide xserver and gtk/gdk versions.

**Comment by airbete** [comment]
xorg-x11-server-Xorg-1.20.8-1.fc32.x86_64
gtk+-1.2.10-93.fc32.x86_64
gtk3-3.24.21-1.fc32.x86_64
gdk-pixbuf2-2.40.0-2.fc32.x86_64

**Comment by bk138** [comment]
Looks like #49 is related.

**Comment by bk138** [comment]
Please try with a587772200cb02ce0d49473dd3903936367e868f

**Comment by airbete** [comment]
It launches with no error now.

`./gromit-mpx -d `

Supported backends: x11 wayland 
Using backend: x11
DEBUG: Ungrabbed all Devices.
DEBUG: Grabbing hotkeys 'F9' and 'F8' from keyboard '3' .
Enabled Device 0: "Core Pointer", (Type: 0)
Now 1 enabled devices.
DEBUG: Ungrabbed all Devices.
DEBUG: Hiding window.
DEBUG: got configure event

However, I was unable to draw anything. The F9 key doesn't work. The app is in the systray (but no icon!) and toggling painting or visibility with the menu has no effect.

There are some warnings in the compilation. I've attached them in case they are relevant:
[compilation.txt](https://github.com/bk138/gromit-mpx/files/5022421/compilation.txt)

**Comment by bk138** [comment]
No systray icon is normal in case you start like this. `build/gromit-mpx -d` should work.

**Comment by bk138** [comment]
Found [this](https://lists.fedoraproject.org/archives/list/kde@lists.fedoraproject.org/thread/OIYKLSEWALYOBUB6KSDWRIFMOFXSSGCU/). Can you try `unset GDK_CORE_DEVICE_EVENTS` and then start gromit-mpx?

**Comment by airbete** [comment]
> Found [this](https://lists.fedoraproject.org/archives/list/kde@lists.fedoraproject.org/thread/OIYKLSEWALYOBUB6KSDWRIFMOFXSSGCU/). Can you try `unset GDK_CORE_DEVICE_EVENTS` and then start gromit-mpx?

Hotkeys F9/F8 now working, and I can draw on screen. Nice!

In the systray menu, "Toggle Painting" doesn't work, but the other actions look fine.

Thank you!
