### ISSUE TITLE
Opacity is wrong when started via .xsessionrc

### ISSUE THREAD

**Issue by sheeptk** [bk138/gromit-mpx#96]
**Description of the bug**

I start gromit-mpx by having the following line in my .xsessionrc:

`gromit-mpx --key Pause --undo-key Scroll_Lock -o 1.0 &`

But the `-o 1.0` switch is just being ignored, I rather get some lower opacity, feels like 70%.

However, if I terminate gromit-mpx (Alt-Pause) and then manually restart it (typing in just the same line as above into my terminal), then it works as expected (runs with 100% opacity).

What is going wrong here?

**Version**

1.3

**Comment by bk138** [comment]
Please try putting the commmand in quotes and shifting around arguments, Keep an eye on the X session logs, watch out for "Opacity set to:" ...

**Comment by sheeptk** [comment]
Thank you for your reply.

I redirected both stdout and stderr to some files, in order to check the output.  The stdout file is empty, the stderr file reads as follows:

`Opacity set to: 1,00`
`skipped token`
`skipped token`
`skipped token`
`Supported backends: x11 wayland `
`Using backend: x11`
`Enabled Device 0: "Virtual core pointer", (Type: 0)`
`Now 1 enabled devices.`

So the opacity is reported as 1.0, but nevertheless when I draw, the real opacity is NOT 1.0, but somewhat lower.

What irritates me, too, is that the reported value uses a comma as a decimal separator, not a dot.  Is it possible that the problem is due to some language settings (German)?

**Comment by sheeptk** [comment]
Quotes don't help, either.  I tried several versions: In most cases the program doesn't start at all, in other cases it just behaves as before.

Changing the order of the arguments doesn't help, either.

**Comment by bk138** [comment]
Hope https://github.com/bk138/gromit-mpx/commit/e7b9594b9ec7015ef019377c8fac7b2aea2b19bf works for you, it did for me!

**Comment by sheeptk** [comment]
No, this doesn't help.  This doesn't start gromit_mpx at all for me.

**Comment by bk138** [comment]
> No, this doesn't help. This doesn't start gromit_mpx at all for me.

The value parsing is locale-specific, hard to say at which point this is set in your X startup. You might try with `-o 1` to be safe.

**Comment by bk138** [comment]
I had
```
[Desktop Entry]
Type=Application
Exec=gromit-mpx -o 1
```
and this worked.

**Comment by sheeptk** [comment]
Good idea to write `-o 1` instead of `-o 1.0`.  But it doesn't work.  Same behaviour as before.

Anything in `.config/autostart/` seems to have no effect at all.

The main question still is: How can it be that the program displays `Opacity set to: 1,00` and nevertheless draws with a lower opacity?
