### ISSUE TITLE
Can't change the hotkeys using config file

### ISSUE THREAD

**Issue by ritterob** [bk138/gromit-mpx#99]
I'm running Linux (Ubuntu/Debian derivative, kernel 5.4, with KDE, xorg 1:7.7, gromit-mpx 1.3-1.) When I try to map the hotkeys in the gromit-mpx.cfg file per the example on github I get an error telling me: "Expected name of tool to define." When I comment the lines out everything works fine.

**Comment by bk138** [comment]
Please post your config. My magic glass ball is currently out of order ;-)

**Comment by ritterob** [comment]
Actually, I used the exact config listed in the project's data directory. Uncommenting the HOTKEY command produced the error.

**Comment by bk138** [comment]
You have to upgrade to a version > 1.3. Support for this was added in 1.3.1.
